/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Connections (void);
GtkWidget* create_AddConnection (void);
GtkWidget* create_RemoteMachine (void);
GtkWidget* create_LocalExecutable (void);
GtkWidget* create_ConnectTerminal (void);
GtkWidget* create_Troubleshooting (void);
GtkWidget* create_ViewLog (void);
