#ifdef MPW_Rez
read 'File' (1000,"cmdhelp") $$Shell("Dat") "cmdhelp";
read 'File' (1001,"help") $$Shell("Dat") "help";
read 'File' (1002,"hh") $$Shell("Dat") "hh";
read 'File' (1003,"history") $$Shell("Dat") "history";
read 'File' (1004,"license") $$Shell("Dat") "license";
read 'File' (1005,"MacHelp") $$Shell("MacDir") "MacHelp";
read 'File' (1006,"News") $$Shell("MacDir") "News";
read 'File' (1007,"opthelp") $$Shell("Dat") "opthelp";
read 'File' (1008,"wizhelp") $$Shell("Dat") "wizhelp";
read 'File' (1009,"data") $$Shell("ObjDir") "data";
read 'File' (1010,"dungeon") $$Shell("ObjDir") "dungeon";
read 'File' (1011,"options") $$Shell("ObjDir") "options";
read 'File' (1012,"oracles") $$Shell("ObjDir") "oracles";
read 'File' (1013,"quest.dat") $$Shell("ObjDir") "quest.dat";
read 'File' (1014,"rumors") $$Shell("ObjDir") "rumors";

read 'File' (1015,"air.lev") $$Shell("ObjDir") "air.lev";
read 'File' (1016,"Arc-fila.lev") $$Shell("ObjDir") "Arc-fila.lev";
read 'File' (1017,"Arc-filb.lev") $$Shell("ObjDir") "Arc-filb.lev";
read 'File' (1018,"Arc-goal.lev") $$Shell("ObjDir") "Arc-goal.lev";
read 'File' (1019,"Arc-loca.lev") $$Shell("ObjDir") "Arc-loca.lev";
read 'File' (1020,"Arc-strt.lev") $$Shell("ObjDir") "Arc-strt.lev";
read 'File' (1021,"asmodeus.lev") $$Shell("ObjDir") "asmodeus.lev";
read 'File' (1022,"astral.lev") $$Shell("ObjDir") "astral.lev";
read 'File' (1023,"baalz.lev") $$Shell("ObjDir") "baalz.lev";
read 'File' (1024,"Bar-fila.lev") $$Shell("ObjDir") "Bar-fila.lev";
read 'File' (1025,"Bar-filb.lev") $$Shell("ObjDir") "Bar-filb.lev";
read 'File' (1026,"Bar-goal.lev") $$Shell("ObjDir") "Bar-goal.lev";
read 'File' (1027,"Bar-loca.lev") $$Shell("ObjDir") "Bar-loca.lev";
read 'File' (1028,"Bar-strt.lev") $$Shell("ObjDir") "Bar-strt.lev";
read 'File' (1029,"beholder.lev") $$Shell("ObjDir") "beholder.lev";
read 'File' (1030,"bigrm-1.lev") $$Shell("ObjDir") "bigrm-1.lev";
read 'File' (1031,"bigrm-2.lev") $$Shell("ObjDir") "bigrm-2.lev";
read 'File' (1032,"bigrm-3.lev") $$Shell("ObjDir") "bigrm-3.lev";
read 'File' (1033,"bigrm-4.lev") $$Shell("ObjDir") "bigrm-4.lev";
read 'File' (1034,"bigrm-5.lev") $$Shell("ObjDir") "bigrm-5.lev";
read 'File' (1035,"blkmar.lev") $$Shell("ObjDir") "blkmar.lev";
read 'File' (1036,"castle.lev") $$Shell("ObjDir") "castle.lev";
read 'File' (1037,"Cav-fila.lev") $$Shell("ObjDir") "Cav-fila.lev";
read 'File' (1038,"Cav-filb.lev") $$Shell("ObjDir") "Cav-filb.lev";
read 'File' (1039,"Cav-goal.lev") $$Shell("ObjDir") "Cav-goal.lev";
read 'File' (1040,"Cav-loca.lev") $$Shell("ObjDir") "Cav-loca.lev";
read 'File' (1041,"Cav-strt.lev") $$Shell("ObjDir") "Cav-strt.lev";
read 'File' (1042,"cav2fill.lev") $$Shell("ObjDir") "cav2fill.lev";
read 'File' (1043,"cavefill.lev") $$Shell("ObjDir") "cavefill.lev";
read 'File' (1044,"demogorg.lev") $$Shell("ObjDir") "demogorg.lev";
read 'File' (1045,"dispater.lev") $$Shell("ObjDir") "dispater.lev";
read 'File' (1051,"dragons.lev") $$Shell("ObjDir") "dragons.lev";
read 'File' (1062,"earth.lev") $$Shell("ObjDir") "earth.lev";
read 'File' (1068,"fakewiz1.lev") $$Shell("ObjDir") "fakewiz1.lev";
read 'File' (1069,"fakewiz2.lev") $$Shell("ObjDir") "fakewiz2.lev";
read 'File' (1070,"fire.lev") $$Shell("ObjDir") "fire.lev";
read 'File' (1071,"Fla-fila.lev") $$Shell("ObjDir") "Fla-fila.lev";
read 'File' (1072,"Fla-filb.lev") $$Shell("ObjDir") "Fla-filb.lev";
read 'File' (1073,"Fla-goal.lev") $$Shell("ObjDir") "Fla-goal.lev";
read 'File' (1074,"Fla-loca.lev") $$Shell("ObjDir") "Fla-loca.lev";
read 'File' (1075,"Fla-strt.lev") $$Shell("ObjDir") "Fla-strt.lev";
read 'File' (1076,"frnknstn.lev") $$Shell("ObjDir") "frnknstn.lev";
read 'File' (1077,"geryon.lev") $$Shell("ObjDir") "geryon.lev";
read 'File' (1083,"guild.lev") $$Shell("ObjDir") "guild.lev";
read 'File' (1084,"Hea-fila.lev") $$Shell("ObjDir") "Hea-fila.lev";
read 'File' (1085,"Hea-filb.lev") $$Shell("ObjDir") "Hea-filb.lev";
read 'File' (1086,"Hea-goal.lev") $$Shell("ObjDir") "Hea-goal.lev";
read 'File' (1087,"Hea-loca.lev") $$Shell("ObjDir") "Hea-loca.lev";
read 'File' (1088,"Hea-strt.lev") $$Shell("ObjDir") "Hea-strt.lev";
read 'File' (1094,"Ice-fila.lev") $$Shell("ObjDir") "Ice-fila.lev";
read 'File' (1095,"Ice-filb.lev") $$Shell("ObjDir") "Ice-filb.lev";
read 'File' (1096,"Ice-goal.lev") $$Shell("ObjDir") "Ice-goal.lev";
read 'File' (1097,"Ice-loca.lev") $$Shell("ObjDir") "Ice-loca.lev";
read 'File' (1098,"Ice-strt.lev") $$Shell("ObjDir") "Ice-strt.lev";
read 'File' (1099,"juiblex.lev") $$Shell("ObjDir") "juiblex.lev";
read 'File' (1100,"Kni-fila.lev") $$Shell("ObjDir") "Kni-fila.lev";
read 'File' (1101,"Kni-filb.lev") $$Shell("ObjDir") "Kni-filb.lev";
read 'File' (1102,"Kni-goal.lev") $$Shell("ObjDir") "Kni-goal.lev";
read 'File' (1103,"Kni-loca.lev") $$Shell("ObjDir") "Kni-loca.lev";
read 'File' (1104,"Kni-strt.lev") $$Shell("ObjDir") "Kni-strt.lev";
read 'File' (1105,"knox.lev") $$Shell("ObjDir") "knox.lev";
read 'File' (1106,"kobold-1.lev") $$Shell("ObjDir") "kobold-1.lev";
read 'File' (1107,"kobold-2.lev") $$Shell("ObjDir") "kobold-2.lev";
read 'File' (1108,"lich.lev") $$Shell("ObjDir") "lich.lev";
read 'File' (1114,"mall-1.lev") $$Shell("ObjDir") "mall-1.lev";
read 'File' (1115,"mall-2.lev") $$Shell("ObjDir") "mall-2.lev";
read 'File' (1116,"mall.lev") $$Shell("ObjDir") "mall.lev";
read 'File' (1117,"medusa-1.lev") $$Shell("ObjDir") "medusa-1.lev";
read 'File' (1118,"medusa-2.lev") $$Shell("ObjDir") "medusa-2.lev";
read 'File' (1119,"minefill.lev") $$Shell("ObjDir") "minefill.lev";
read 'File' (1120,"mineking.lev") $$Shell("ObjDir") "mineking.lev";
read 'File' (1121,"minend-1.lev") $$Shell("ObjDir") "minend-1.lev";
read 'File' (1122,"minend-2.lev") $$Shell("ObjDir") "minend-2.lev";
read 'File' (1123,"minetn-1.lev") $$Shell("ObjDir") "minetn-1.lev";
read 'File' (1124,"minetn-2.lev") $$Shell("ObjDir") "minetn-2.lev";
read 'File' (1125,"Mon-fila.lev") $$Shell("ObjDir") "Mon-fila.lev";
read 'File' (1126,"Mon-filb.lev") $$Shell("ObjDir") "Mon-filb.lev";
read 'File' (1127,"Mon-goal.lev") $$Shell("ObjDir") "Mon-goal.lev";
read 'File' (1128,"Mon-loca.lev") $$Shell("ObjDir") "Mon-loca.lev";
read 'File' (1129,"Mon-strt.lev") $$Shell("ObjDir") "Mon-strt.lev";
read 'File' (1130,"mtemple.lev") $$Shell("ObjDir") "mtemple.lev";
read 'File' (1131,"Nec-fila.lev") $$Shell("ObjDir") "Nec-fila.lev";
read 'File' (1132,"Nec-filb.lev") $$Shell("ObjDir") "Nec-filb.lev";
read 'File' (1133,"Nec-goal.lev") $$Shell("ObjDir") "Nec-goal.lev";
read 'File' (1134,"Nec-loca.lev") $$Shell("ObjDir") "Nec-loca.lev";
read 'File' (1135,"Nec-strt.lev") $$Shell("ObjDir") "Nec-strt.lev";
read 'File' (1136,"nightmar.lev") $$Shell("ObjDir") "nightmar.lev";
read 'File' (1137,"nymph.lev") $$Shell("ObjDir") "nymph.lev";
read 'File' (1138,"oracle.lev") $$Shell("ObjDir") "oracle.lev";
read 'File' (1139,"orcus.lev") $$Shell("ObjDir") "orcus.lev";
read 'File' (1140,"Pri-fila.lev") $$Shell("ObjDir") "Pri-fila.lev";
read 'File' (1141,"Pri-filb.lev") $$Shell("ObjDir") "Pri-filb.lev";
read 'File' (1142,"Pri-goal.lev") $$Shell("ObjDir") "Pri-goal.lev";
read 'File' (1143,"Pri-loca.lev") $$Shell("ObjDir") "Pri-loca.lev";
read 'File' (1144,"Pri-strt.lev") $$Shell("ObjDir") "Pri-strt.lev";
read 'File' (1145,"Ran-fila.lev") $$Shell("ObjDir") "Ran-fila.lev";
read 'File' (1146,"Ran-filb.lev") $$Shell("ObjDir") "Ran-filb.lev";
read 'File' (1147,"Ran-goal.lev") $$Shell("ObjDir") "Ran-goal.lev";
read 'File' (1148,"Ran-loca.lev") $$Shell("ObjDir") "Ran-loca.lev";
read 'File' (1149,"Ran-strt.lev") $$Shell("ObjDir") "Ran-strt.lev";
read 'File' (1150,"rats.lev") $$Shell("ObjDir") "rats.lev";
read 'File' (1151,"Rog-fila.lev") $$Shell("ObjDir") "Rog-fila.lev";
read 'File' (1152,"Rog-filb.lev") $$Shell("ObjDir") "Rog-filb.lev";
read 'File' (1153,"Rog-goal.lev") $$Shell("ObjDir") "Rog-goal.lev";
read 'File' (1154,"Rog-loca.lev") $$Shell("ObjDir") "Rog-loca.lev";
read 'File' (1155,"Rog-strt.lev") $$Shell("ObjDir") "Rog-strt.lev";
read 'File' (1156,"Sam-fila.lev") $$Shell("ObjDir") "Sam-fila.lev";
read 'File' (1157,"Sam-filb.lev") $$Shell("ObjDir") "Sam-filb.lev";
read 'File' (1158,"Sam-goal.lev") $$Shell("ObjDir") "Sam-goal.lev";
read 'File' (1159,"Sam-loca.lev") $$Shell("ObjDir") "Sam-loca.lev";
read 'File' (1160,"Sam-strt.lev") $$Shell("ObjDir") "Sam-strt.lev";
read 'File' (1161,"sanctum.lev") $$Shell("ObjDir") "sanctum.lev";
read 'File' (1162,"sea.lev") $$Shell("ObjDir") "sea.lev";
read 'File' (1163,"soko1-1.lev") $$Shell("ObjDir") "soko1-1.lev";
read 'File' (1164,"soko1-2.lev") $$Shell("ObjDir") "soko1-2.lev";
read 'File' (1165,"soko2-1.lev") $$Shell("ObjDir") "soko2-1.lev";
read 'File' (1166,"soko2-2.lev") $$Shell("ObjDir") "soko2-2.lev";
read 'File' (1167,"soko3-1.lev") $$Shell("ObjDir") "soko3-1.lev";
read 'File' (1168,"soko3-2.lev") $$Shell("ObjDir") "soko3-2.lev";
read 'File' (1169,"soko4-1.lev") $$Shell("ObjDir") "soko4-1.lev";
read 'File' (1170,"soko4-2.lev") $$Shell("ObjDir") "soko4-2.lev";
read 'File' (1171,"spiders.lev") $$Shell("ObjDir") "spiders.lev";
read 'File' (1172,"stor-1.lev") $$Shell("ObjDir") "stor-1.lev";
read 'File' (1173,"stor-2.lev") $$Shell("ObjDir") "stor-2.lev";
read 'File' (1174,"stor-3.lev") $$Shell("ObjDir") "stor-3.lev";
read 'File' (1175,"tomb.lev") $$Shell("ObjDir") "tomb.lev";
read 'File' (1176,"Tou-fila.lev") $$Shell("ObjDir") "Tou-fila.lev";
read 'File' (1177,"Tou-filb.lev") $$Shell("ObjDir") "Tou-filb.lev";
read 'File' (1178,"Tou-goal.lev") $$Shell("ObjDir") "Tou-goal.lev";
read 'File' (1179,"Tou-loca.lev") $$Shell("ObjDir") "Tou-loca.lev";
read 'File' (1180,"Tou-strt.lev") $$Shell("ObjDir") "Tou-strt.lev";
read 'File' (1181,"tower1.lev") $$Shell("ObjDir") "tower1.lev";
read 'File' (1182,"tower2.lev") $$Shell("ObjDir") "tower2.lev";
read 'File' (1183,"tower3.lev") $$Shell("ObjDir") "tower3.lev";
read 'File' (1184,"Und-fila.lev") $$Shell("ObjDir") "Und-fila.lev";
read 'File' (1185,"Und-filb.lev") $$Shell("ObjDir") "Und-filb.lev";
read 'File' (1186,"Und-goal.lev") $$Shell("ObjDir") "Und-goal.lev";
read 'File' (1187,"Und-loca.lev") $$Shell("ObjDir") "Und-loca.lev";
read 'File' (1188,"Und-strt.lev") $$Shell("ObjDir") "Und-strt.lev";
read 'File' (1189,"Val-fila.lev") $$Shell("ObjDir") "Val-fila.lev";
read 'File' (1190,"Val-filb.lev") $$Shell("ObjDir") "Val-filb.lev";
read 'File' (1191,"Val-goal.lev") $$Shell("ObjDir") "Val-goal.lev";
read 'File' (1192,"Val-loca.lev") $$Shell("ObjDir") "Val-loca.lev";
read 'File' (1193,"Val-strt.lev") $$Shell("ObjDir") "Val-strt.lev";
read 'File' (1194,"valley.lev") $$Shell("ObjDir") "valley.lev";
read 'File' (1195,"water.lev") $$Shell("ObjDir") "water.lev";
read 'File' (1196,"Wiz-fila.lev") $$Shell("ObjDir") "Wiz-fila.lev";
read 'File' (1197,"Wiz-filb.lev") $$Shell("ObjDir") "Wiz-filb.lev";
read 'File' (1198,"Wiz-goal.lev") $$Shell("ObjDir") "Wiz-goal.lev";
read 'File' (1199,"Wiz-loca.lev") $$Shell("ObjDir") "Wiz-loca.lev";
read 'File' (1200,"Wiz-strt.lev") $$Shell("ObjDir") "Wiz-strt.lev";
read 'File' (1201,"wizard1.lev") $$Shell("ObjDir") "wizard1.lev";
read 'File' (1202,"wizard2.lev") $$Shell("ObjDir") "wizard2.lev";
read 'File' (1203,"wizard3.lev") $$Shell("ObjDir") "wizard3.lev";
read 'File' (1204,"yeenoghu.lev") $$Shell("ObjDir") "yeenoghu.lev";
read 'File' (1205,"Yeo-fila.lev") $$Shell("ObjDir") "Yeo-fila.lev";
read 'File' (1206,"Yeo-filb.lev") $$Shell("ObjDir") "Yeo-filb.lev";
read 'File' (1207,"Yeo-goal.lev") $$Shell("ObjDir") "Yeo-goal.lev";
read 'File' (1208,"Yeo-loca.lev") $$Shell("ObjDir") "Yeo-loca.lev";
read 'File' (1209,"Yeo-strt.lev") $$Shell("ObjDir") "Yeo-strt.lev";

read 'File' (1210,"Guidebook.txt") $$Shell("Results") "Guidebook.txt";
#else
read 'File' (1000,"cmdhelp") "cmdhelp";
read 'File' (1001,"help") "help";
read 'File' (1002,"hh") "hh";
read 'File' (1003,"history") "history";
read 'File' (1004,"license") "license";
read 'File' (1005,"MacHelp") "MacHelp";
read 'File' (1006,"News") "News";
read 'File' (1007,"opthelp") "opthelp";
read 'File' (1008,"wizhelp") "wizhelp";
read 'File' (1009,"data") "data";
read 'File' (1010,"dungeon") "dungeon";
read 'File' (1011,"options") "options";
read 'File' (1012,"oracles") "oracles";
read 'File' (1013,"quest.dat") "quest.dat";
read 'File' (1014,"rumors") "rumors";

read 'File' (1015,"air.lev") "air.lev";
read 'File' (1016,"Arc-fila.lev") "Arc-fila.lev";
read 'File' (1017,"Arc-filb.lev") "Arc-filb.lev";
read 'File' (1018,"Arc-goal.lev") "Arc-goal.lev";
read 'File' (1019,"Arc-loca.lev") "Arc-loca.lev";
read 'File' (1020,"Arc-strt.lev") "Arc-strt.lev";
read 'File' (1021,"asmodeus.lev") "asmodeus.lev";
read 'File' (1022,"astral.lev") "astral.lev";
read 'File' (1023,"baalz.lev") "baalz.lev";
read 'File' (1024,"Bar-fila.lev") "Bar-fila.lev";
read 'File' (1025,"Bar-filb.lev") "Bar-filb.lev";
read 'File' (1026,"Bar-goal.lev") "Bar-goal.lev";
read 'File' (1027,"Bar-loca.lev") "Bar-loca.lev";
read 'File' (1028,"Bar-strt.lev") "Bar-strt.lev";
read 'File' (1029,"beholder.lev") "beholder.lev";
read 'File' (1030,"bigrm-1.lev") "bigrm-1.lev";
read 'File' (1031,"bigrm-2.lev") "bigrm-2.lev";
read 'File' (1032,"bigrm-3.lev") "bigrm-3.lev";
read 'File' (1033,"bigrm-4.lev") "bigrm-4.lev";
read 'File' (1034,"bigrm-5.lev") "bigrm-5.lev";
read 'File' (1035,"blkmar.lev") "blkmar.lev";
read 'File' (1036,"castle.lev") "castle.lev";
read 'File' (1037,"Cav-fila.lev") "Cav-fila.lev";
read 'File' (1038,"Cav-filb.lev") "Cav-filb.lev";
read 'File' (1039,"Cav-goal.lev") "Cav-goal.lev";
read 'File' (1040,"Cav-loca.lev") "Cav-loca.lev";
read 'File' (1041,"Cav-strt.lev") "Cav-strt.lev";
read 'File' (1042,"cav2fill.lev") "cav2fill.lev";
read 'File' (1043,"cavefill.lev") "cavefill.lev";
read 'File' (1044,"demogorg.lev") "demogorg.lev";
read 'File' (1045,"dispater.lev") "dispater.lev";
read 'File' (1051,"dragons.lev") "dragons.lev";
read 'File' (1062,"earth.lev") "earth.lev";
read 'File' (1068,"fakewiz1.lev") "fakewiz1.lev";
read 'File' (1069,"fakewiz2.lev") "fakewiz2.lev";
read 'File' (1070,"fire.lev") "fire.lev";
read 'File' (1071,"Fla-fila.lev") "Fla-fila.lev";
read 'File' (1072,"Fla-filb.lev") "Fla-filb.lev";
read 'File' (1073,"Fla-goal.lev") "Fla-goal.lev";
read 'File' (1074,"Fla-loca.lev") "Fla-loca.lev";
read 'File' (1075,"Fla-strt.lev") "Fla-strt.lev";
read 'File' (1076,"frnknstn.lev") "frnknstn.lev";
read 'File' (1077,"geryon.lev") "geryon.lev";
read 'File' (1083,"guild.lev") "guild.lev";
read 'File' (1084,"Hea-fila.lev") "Hea-fila.lev";
read 'File' (1085,"Hea-filb.lev") "Hea-filb.lev";
read 'File' (1086,"Hea-goal.lev") "Hea-goal.lev";
read 'File' (1087,"Hea-loca.lev") "Hea-loca.lev";
read 'File' (1088,"Hea-strt.lev") "Hea-strt.lev";
read 'File' (1094,"Ice-fila.lev") "Ice-fila.lev";
read 'File' (1095,"Ice-filb.lev") "Ice-filb.lev";
read 'File' (1096,"Ice-goal.lev") "Ice-goal.lev";
read 'File' (1097,"Ice-loca.lev") "Ice-loca.lev";
read 'File' (1098,"Ice-strt.lev") "Ice-strt.lev";
read 'File' (1099,"juiblex.lev") "juiblex.lev";
read 'File' (1100,"Kni-fila.lev") "Kni-fila.lev";
read 'File' (1101,"Kni-filb.lev") "Kni-filb.lev";
read 'File' (1102,"Kni-goal.lev") "Kni-goal.lev";
read 'File' (1103,"Kni-loca.lev") "Kni-loca.lev";
read 'File' (1104,"Kni-strt.lev") "Kni-strt.lev";
read 'File' (1105,"knox.lev") "knox.lev";
read 'File' (1106,"kobold-1.lev") "kobold-1.lev";
read 'File' (1107,"kobold-2.lev") "kobold-2.lev";
read 'File' (1108,"lich.lev") "lich.lev";
read 'File' (1114,"mall-1.lev") "mall-1.lev";
read 'File' (1115,"mall-2.lev") "mall-2.lev";
read 'File' (1116,"mall.lev") "mall.lev";
read 'File' (1117,"medusa-1.lev") "medusa-1.lev";
read 'File' (1118,"medusa-2.lev") "medusa-2.lev";
read 'File' (1119,"minefill.lev") "minefill.lev";
read 'File' (1120,"mineking.lev") "mineking.lev";
read 'File' (1121,"minend-1.lev") "minend-1.lev";
read 'File' (1122,"minend-2.lev") "minend-2.lev";
read 'File' (1123,"minetn-1.lev") "minetn-1.lev";
read 'File' (1124,"minetn-2.lev") "minetn-2.lev";
read 'File' (1125,"Mon-fila.lev") "Mon-fila.lev";
read 'File' (1126,"Mon-filb.lev") "Mon-filb.lev";
read 'File' (1127,"Mon-goal.lev") "Mon-goal.lev";
read 'File' (1128,"Mon-loca.lev") "Mon-loca.lev";
read 'File' (1129,"Mon-strt.lev") "Mon-strt.lev";
read 'File' (1130,"mtemple.lev") "mtemple.lev";
read 'File' (1131,"Nec-fila.lev") "Nec-fila.lev";
read 'File' (1132,"Nec-filb.lev") "Nec-filb.lev";
read 'File' (1133,"Nec-goal.lev") "Nec-goal.lev";
read 'File' (1134,"Nec-loca.lev") "Nec-loca.lev";
read 'File' (1135,"Nec-strt.lev") "Nec-strt.lev";
read 'File' (1136,"nightmar.lev") "nightmar.lev";
read 'File' (1137,"nymph.lev") "nymph.lev";
read 'File' (1138,"oracle.lev") "oracle.lev";
read 'File' (1139,"orcus.lev") "orcus.lev";
read 'File' (1140,"Pri-fila.lev") "Pri-fila.lev";
read 'File' (1141,"Pri-filb.lev") "Pri-filb.lev";
read 'File' (1142,"Pri-goal.lev") "Pri-goal.lev";
read 'File' (1143,"Pri-loca.lev") "Pri-loca.lev";
read 'File' (1144,"Pri-strt.lev") "Pri-strt.lev";
read 'File' (1145,"Ran-fila.lev") "Ran-fila.lev";
read 'File' (1146,"Ran-filb.lev") "Ran-filb.lev";
read 'File' (1147,"Ran-goal.lev") "Ran-goal.lev";
read 'File' (1148,"Ran-loca.lev") "Ran-loca.lev";
read 'File' (1149,"Ran-strt.lev") "Ran-strt.lev";
read 'File' (1150,"rats.lev") "rats.lev";
read 'File' (1151,"Rog-fila.lev") "Rog-fila.lev";
read 'File' (1152,"Rog-filb.lev") "Rog-filb.lev";
read 'File' (1153,"Rog-goal.lev") "Rog-goal.lev";
read 'File' (1154,"Rog-loca.lev") "Rog-loca.lev";
read 'File' (1155,"Rog-strt.lev") "Rog-strt.lev";
read 'File' (1156,"Sam-fila.lev") "Sam-fila.lev";
read 'File' (1157,"Sam-filb.lev") "Sam-filb.lev";
read 'File' (1158,"Sam-goal.lev") "Sam-goal.lev";
read 'File' (1159,"Sam-loca.lev") "Sam-loca.lev";
read 'File' (1160,"Sam-strt.lev") "Sam-strt.lev";
read 'File' (1161,"sanctum.lev") "sanctum.lev";
read 'File' (1162,"sea.lev") "sea.lev";
read 'File' (1163,"soko1-1.lev") "soko1-1.lev";
read 'File' (1164,"soko1-2.lev") "soko1-2.lev";
read 'File' (1165,"soko2-1.lev") "soko2-1.lev";
read 'File' (1166,"soko2-2.lev") "soko2-2.lev";
read 'File' (1167,"soko3-1.lev") "soko3-1.lev";
read 'File' (1168,"soko3-2.lev") "soko3-2.lev";
read 'File' (1169,"soko4-1.lev") "soko4-1.lev";
read 'File' (1170,"soko4-2.lev") "soko4-2.lev";
read 'File' (1171,"spiders.lev") "spiders.lev";
read 'File' (1172,"stor-1.lev") "stor-1.lev";
read 'File' (1173,"stor-2.lev") "stor-2.lev";
read 'File' (1174,"stor-3.lev") "stor-3.lev";
read 'File' (1175,"tomb.lev") "tomb.lev";
read 'File' (1176,"Tou-fila.lev") "Tou-fila.lev";
read 'File' (1177,"Tou-filb.lev") "Tou-filb.lev";
read 'File' (1178,"Tou-goal.lev") "Tou-goal.lev";
read 'File' (1179,"Tou-loca.lev") "Tou-loca.lev";
read 'File' (1180,"Tou-strt.lev") "Tou-strt.lev";
read 'File' (1181,"tower1.lev") "tower1.lev";
read 'File' (1182,"tower2.lev") "tower2.lev";
read 'File' (1183,"tower3.lev") "tower3.lev";
read 'File' (1184,"Und-fila.lev") "Und-fila.lev";
read 'File' (1185,"Und-filb.lev") "Und-filb.lev";
read 'File' (1186,"Und-goal.lev") "Und-goal.lev";
read 'File' (1187,"Und-loca.lev") "Und-loca.lev";
read 'File' (1188,"Und-strt.lev") "Und-strt.lev";
read 'File' (1189,"Val-fila.lev") "Val-fila.lev";
read 'File' (1190,"Val-filb.lev") "Val-filb.lev";
read 'File' (1191,"Val-goal.lev") "Val-goal.lev";
read 'File' (1192,"Val-loca.lev") "Val-loca.lev";
read 'File' (1193,"Val-strt.lev") "Val-strt.lev";
read 'File' (1194,"valley.lev") "valley.lev";
read 'File' (1195,"water.lev") "water.lev";
read 'File' (1196,"Wiz-fila.lev") "Wiz-fila.lev";
read 'File' (1197,"Wiz-filb.lev") "Wiz-filb.lev";
read 'File' (1198,"Wiz-goal.lev") "Wiz-goal.lev";
read 'File' (1199,"Wiz-loca.lev") "Wiz-loca.lev";
read 'File' (1200,"Wiz-strt.lev") "Wiz-strt.lev";
read 'File' (1201,"wizard1.lev") "wizard1.lev";
read 'File' (1202,"wizard2.lev") "wizard2.lev";
read 'File' (1203,"wizard3.lev") "wizard3.lev";
read 'File' (1204,"yeenoghu.lev") "yeenoghu.lev";
read 'File' (1205,"Yeo-fila.lev") "Yeo-fila.lev";
read 'File' (1206,"Yeo-filb.lev") "Yeo-filb.lev";
read 'File' (1207,"Yeo-goal.lev") "Yeo-goal.lev";
read 'File' (1208,"Yeo-loca.lev") "Yeo-loca.lev";
read 'File' (1209,"Yeo-strt.lev") "Yeo-strt.lev";

read 'File' (1210,"Guidebook.txt") "Guidebook.txt";
#endif
