/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cygdrive/d/Daten/Repositories/slashem-cvs/slashem/sys/share/lev_lex.c,v 1.5 2003-02-19 15:39:14 j_ali Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 120
#define YY_END_OF_BUFFER 121
static yyconst short int yy_accept[672] =
    {   0,
        0,    0,    0,    0,  121,  119,  116,  115,  119,  119,
      119,  113,    4,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
        2,  116,  119,  119,  113,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  116,    0,  114,
        0,    0,  113,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   90,    0,    0,    3,    0,    2,  116,    0,  113,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,
      118,    0,  118,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   75,    0,    0,    0,   70,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   68,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  117,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,   42,
        0,    0,    0,    6,    0,    0,   44,    0,    0,    0,

        0,   35,    0,    0,    0,   38,   34,    0,    0,    0,
       17,    0,    0,  112,    0,    0,    0,    0,    0,    0,
        0,    0,   96,    0,    0,    0,    0,    0,    0,   91,
       94,   53,    0,    0,    0,    0,    0,    0,   63,    0,
        0,    0,    0,    0,    0,   97,    0,    0,    0,    0,
        0,    0,   57,    0,    0,    0,    0,    0,   47,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       93,    0,    0,    0,   55,   12,    0,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,   10,    0,    0,
        0,    0,    8,    0,    0,    0,    7,    0,    0,    0,

        0,    0,    0,    0,   28,    0,    0,    0,   61,   89,
        0,    0,   83,    0,    0,    0,    0,   77,    0,    0,
        0,    0,    0,   92,    0,    0,    0,    0,  111,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       52,    0,    0,  103,    0,    0,   60,    0,    0,   67,
        0,    0,    0,    0,   54,    0,    0,    0,   71,    0,
        0,   32,   45,    0,    0,    0,    0,    0,    0,    0,
       27,    0,    0,    0,    0,    0,   13,    0,   29,    0,
       22,    0,    0,    0,    0,   82,    0,   69,   51,   65,
       48,    0,    0,  101,    0,   72,    0,    0,    0,    0,

        0,   49,    0,    0,    0,    0,    0,    0,   50,  107,
        0,    0,    0,   58,    0,   56,   62,    0,   98,    0,
       88,  110,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    5,   16,    0,    0,    0,    0,
       39,    0,   21,    0,   99,    0,    0,   95,    0,    0,
        0,   81,    0,    0,    0,    0,   59,   76,   74,    0,
        0,    0,    0,   87,    0,    0,    0,    0,   41,    0,
        0,   33,   11,    9,   20,    0,    0,   14,    0,    0,
        0,    0,    0,    0,  108,    0,    0,    0,    0,    0,
        0,    0,    0,   86,    0,    0,  104,   80,    0,  100,

       73,   15,    0,   43,    0,    0,    0,    0,    0,    0,
        0,    0,   78,  102,   64,    0,  106,   46,   84,   85,
        0,    0,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,   66,    0,  105,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   36,   37,    0,    0,
        0,    0,    0,    0,   79,  109,    0,    0,    0,   25,
       31,    0,    0,    0,   23,    0,    0,   24,   30,   40,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    8,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,   37,
       38,   39,   40,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    1,   58,   59,   60,   61,   62,   63,    1,
       64,    1,   11,   11,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    2,    3,    2,    1,    2,    1,    1,    2,    2,
        2,    2,    1,    2,    2,    2,    1,    1,    2,    1,
        2,    2,    1,    2,    2,    1,    1,    1,    2,    1,
        2,    2,    1,    1,    2,    1,    2,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[677] =
    {   0,
        0,   59,   83,   62,  823,  824,   65,  824,  817,  782,
      808,  807,  824,  793,  787,   45,   42,  789,   46,   62,
      788,   61,   63,   68,  799,  785,   95,   78,   98,  798,
       72,   66,   74,   85,   22,   84,   94,   61,  101,  107,
       94,  111,  107,  116,  123,  103,  114,  765,  807,  156,
      824,  173,  153,  179,  183,  185,  187,  190,  782,  194,
      196,  198,  200,  202,  211,  206,  239,  223,  803,  824,
      799,  798,  793,  772,  789,  788,  115,  773,  786,  779,
      784,  764,  768,  770,  772,  776,  758,  754,  759,  762,
      762,  180,  764,  202,  759,  765,  756,  756,  768,  766,

      755,  765,  753,  227,  166,  176,  734,  723,  733,  728,
      713,  716,  713,  715,  727,  712,  191,  709,  703,  706,
      705,  715,  709,  708,  194,  701,  696,  197,  698,  713,
      219,  698,  700,  693,  227,  224,  702,  706,  709,  708,
      694,  700,  699,  691,  687,  182,  683,  687,  685,  680,
      236,  824,  681,  736,  824,  255,  824,  291,  288,  294,
      296,  298,  245,  300,  302,  305,  307,  313,  824,    0,
      824,  730,  729,  722,  708,  707,  701,  702,  701,  695,
      699,  708,  700,  700,  708,  692,  706,  704,  703,  689,
      688,  700,  703,  675,  299,  690,  682,  696,  690,  685,

      686,  687,  678,  689,  677,  680,  282,  656,  661,  646,
      655,  648,  640,  638,  645,  641,  635,  638,  634,  639,
      631,  631,  634,  628,  627,  628,  626,  631,  636,  637,
      621,  824,  620,  630,  620,  824,  625,  630,  619,  631,
      621,  613,  611,  617,  613,  614,  267,  607,  620,  604,
      614,  617,  607,  617,  616,  614,  608,  608,  612,  613,
      596,  603,  592,  595,  824,  604,  588,  598,  597,  586,
      642,  321,  323,  618,  327,  331,  334,  824,  613,  626,
      625,  626,  617,  824,  623,  623,  605,  603,  616,  824,
      592,  614,  606,  595,  615,  596,  824,  598,  104,  610,

      600,  824,  610,  595,  594,  824,  824,  591,  592,  590,
      824,  596,  316,  824,  562,  558,  557,  568,  567,  553,
      555,  564,  824,  563,  549,  561,  556,  563,  558,  824,
      824,  824,  561,  556,  555,  590,  552,  548,  824,  551,
      550,  549,  552,  538,  541,  824,  531,  532,  539,  532,
      545,  530,  824,  536,  531,  525,  522,  537,  824,  534,
      533,  522,  521,  516,  515,  511,  513,  517,  522,  518,
      824,  511,  515,  507,  824,  824,  337,  552,  339,  341,
      824,  544,  546,  541,  545,  531,  526,  824,  545,  526,
      531,  526,  824,  541,  534,  535,  824,  530,  537,  518,

      535,  523,  521,  519,  824,  517,  516,  524,  824,  824,
      496,  484,  824,  494,  485,  483,  479,  824,  491,  487,
      484,  488,  470,  824,  486,  293,  477,  476,  824,  480,
      482,  466,  466,  478,  477,  480,  473,  462,  462,  476,
      824,  471,  466,  824,  455,  467,  824,  459,  457,  824,
      450,  457,  450,  462,  824,  443,  447,  452,  824,  475,
      346,  824,  824,  476,  474,  479,  478,  477,  468,  483,
      824,  471,  477,  464,  473,  461,  824,  471,  824,  449,
      824,  463,  458,  451,  444,  824,  440,  824,  824,  824,
      824,  429,  428,  824,  436,  824,  435,  430,  423,  432,

      427,  824,  415,  415,  430,  415,  419,  416,  824,  824,
      417,  412,  422,  824,  406,  824,  824,  412,  824,  415,
      824,  824,  418,  417,  824,  352,  444,  431,  443,  432,
      431,  421,  427,  431,  824,  824,  434,  422,  421,  342,
      824,  419,  824,  397,  824,  403,  402,  824,  400,  398,
      389,  824,  388,  385,  396,  381,  824,  824,  824,  390,
      383,  393,  384,  824,  388,  390,  389,  403,  824,  412,
      411,  824,  824,  824,  824,  416,  394,  824,  400,  399,
      411,  400,  406,  382,  824,  377,  376,  360,  370,  360,
      362,  370,  357,  824,  366,  355,  824,  824,  363,  824,

      824,  824,  393,  824,  395,  395,  378,  380,  383,  391,
      384,  373,  824,  824,  824,  342,  824,  824,  824,  824,
      346,  327,  326,  824,  360,  359,  353,  351,  363,  364,
      357,  360,  824,  331,  824,  330,  357,  349,  351,  334,
      348,  344,  333,  340,  312,  307,  824,  824,  328,  313,
      295,  257,  252,  234,  824,  824,  209,  191,  184,  824,
      824,  166,  153,  133,  824,  110,   75,  824,  824,  824,
      824,  388,  391,  393,  395,  398
    } ;

static yyconst short int yy_def[677] =
    {   0,
      671,    1,    1,    3,  671,  671,  671,  671,  672,  673,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  674,  671,
      671,  675,  675,  675,  675,  675,  675,  675,  671,  675,
      675,  675,  675,  675,  675,  675,  674,  671,  672,  671,
      671,  676,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  674,  671,  671,  671,  675,  675,  675,
      675,  675,  671,  675,  675,  675,  675,  675,  671,   67,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  675,  675,  671,  675,  675,  675,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  675,  671,  675,  675,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      675,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  675,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,

      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
        0,  671,  671,  671,  671,  671
    } ;

static yyconst short int yy_nxt[889] =
    {   0,
        6,    7,    8,    7,    9,    6,    6,   10,   11,   11,
        6,   12,   13,   14,   15,   16,   17,   18,   19,   20,
        6,   21,    6,    6,   22,   23,   24,   25,   26,   27,
       28,   29,    6,    6,   30,    6,    6,   31,    6,    6,
        6,   32,   33,   34,   35,   36,   37,    6,   38,    6,
        6,    6,   39,   40,   41,   42,   43,   44,   45,   46,
       47,    6,   48,    6,   49,   76,   68,   67,   68,   78,
       81,   79,   77,   82,   86,  104,   88,  119,   87,   83,
       89,   91,  120,  105,   50,   51,   52,   50,   53,   84,
       90,   54,   54,   53,   55,   92,   56,   57,   58,   98,

       59,   60,  125,   53,   61,  670,   53,   62,   95,   99,
      100,   63,   96,   64,   65,  101,  126,   66,  106,   53,
      398,   53,   97,  107,  108,  121,  110,  102,  109,  111,
      114,  112,  399,  115,  113,  123,  669,  116,  122,  134,
      117,  177,  127,  124,  178,  118,  128,  131,  132,  135,
      129,  136,  139,  137,  671,  157,  130,  141,  149,  140,
      150,  142,  133,  668,  144,  143,  145,  138,  151,  156,
      152,  146,  207,   89,   68,  157,  158,  105,  147,  148,
      671,  157,  667,   90,  671,  157,  671,  157,  671,  157,
      160,  671,  157,  666,  160,  671,  157,  671,  157,  671,

      157,  671,  157,  671,  157,  193,  194,  671,  157,  161,
      162,  165,  671,  157,  665,   87,   75,   77,  164,  168,
      664,   82,   85,  166,   68,  208,   68,   94,  101,  196,
      104,  197,  220,  167,  100,  209,  663,  261,  105,  262,
      102,  169,  170,  233,  170,  221,  229,  170,  170,  170,
      170,  230,  170,  170,  170,  662,  234,  170,  235,  170,
      170,  274,  170,  170,  181,  238,  250,  170,  244,  170,
      170,  245,  239,  170,  240,  170,  251,  170,  661,  267,
      246,  247,  268,  271,  248,  313,  249,  660,  269,  671,
      157,  189,   68,  157,  158,  671,  157,  671,  157,  671,

      157,  671,  157,  671,  157,  160,  671,  157,  671,  157,
      352,  273,  353,  275,  671,  157,  300,  301,  187,  313,
      276,  314,  671,  157,  671,  157,  659,  272,  671,  157,
      658,  201,  671,  157,  377,  671,  157,  277,  671,  157,
      671,  157,  671,  157,  657,  497,  287,  671,  157,  281,
      498,  656,  379,  671,  157,  314,  655,  579,  380,  654,
      653,  652,  461,  651,  526,  650,  381,  580,  405,  581,
      582,  583,  649,  648,  647,  646,  645,  644,  643,  642,
      641,  640,  639,  638,  637,  636,  635,  543,   69,   69,
       69,   71,   71,  154,  154,  154,  159,  159,  172,  172,

      634,  633,  632,  631,  630,  629,  628,  627,  626,  625,
      624,  623,  622,  621,  620,  619,  618,  617,  616,  615,
      614,  613,  612,  611,  610,  609,  608,  607,  606,  605,
      604,  603,  602,  601,  600,  599,  598,  597,  596,  595,
      594,  593,  592,  591,  590,  589,  588,  587,  586,  585,
      584,  578,  577,  576,  575,  574,  573,  572,  571,  570,
      569,  568,  567,  566,  565,  564,  563,  562,  561,  560,
      559,  558,  557,  556,  555,  554,  553,  552,  551,  550,
      549,  548,  547,  546,  545,  544,  543,  542,  541,  540,
      539,  538,  537,  536,  535,  534,  533,  532,  531,  530,

      529,  528,  527,  525,  524,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,

      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  378,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,

      318,  317,  316,  315,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  278,  155,  270,
      266,  265,  264,  263,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  243,  242,  241,  237,  236,  232,  231,
      228,  227,  226,  225,  224,  223,  222,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  195,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,

      179,  176,  175,  174,   73,  173,  171,   70,  163,  155,
      153,  103,   94,   93,   85,   80,   75,   74,   73,   73,
       72,   70,  671,    5,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671
    } ;

static yyconst short int yy_chk[889] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,   16,    7,    4,    7,   17,
       19,   17,   16,   19,   22,   31,   23,   35,   22,   20,
       23,   24,   35,   31,    2,    3,    3,    4,    3,   20,
       23,    3,    3,    3,    3,   24,    3,    3,    3,   28,

        3,    3,   38,    3,    3,  667,    3,    3,   27,   28,
       28,    3,   27,    3,    3,   29,   38,    3,   32,    3,
      299,    3,   27,   32,   32,   36,   33,   29,   32,   33,
       34,   33,  299,   34,   33,   37,  666,   34,   36,   41,
       34,   77,   39,   37,   77,   34,   39,   40,   40,   41,
       39,   42,   43,   42,   53,   53,   39,   44,   46,   43,
       46,   44,   40,  664,   45,   44,   45,   42,   47,   50,
       47,   45,  105,   50,   52,   52,   52,  105,   45,   45,
       54,   54,  663,   50,   55,   55,   56,   56,   57,   57,
       54,   58,   58,  662,   55,   60,   60,   61,   61,   62,

       62,   63,   63,   64,   64,   92,   92,   66,   66,   56,
       58,   62,   65,   65,  659,   62,   57,   58,   60,   66,
      658,   60,   61,   64,   68,  106,   68,   63,   65,   94,
      104,   94,  117,   64,   64,  106,  657,  146,  104,  146,
       65,   67,   67,  128,   67,  117,  125,   67,   67,   67,
       67,  125,   67,   67,   67,  654,  128,   67,  128,   67,
       67,  163,   67,   67,  163,  131,  136,   67,  135,   67,
       67,  135,  131,   67,  131,   67,  136,   67,  653,  151,
      135,  135,  151,  156,  135,  207,  135,  652,  151,  159,
      159,  156,  158,  158,  158,  160,  160,  161,  161,  162,

      162,  164,  164,  165,  165,  160,  166,  166,  167,  167,
      247,  162,  247,  164,  168,  168,  195,  195,  165,  313,
      167,  207,  272,  272,  273,  273,  651,  161,  275,  275,
      650,  166,  276,  276,  272,  277,  277,  168,  377,  377,
      379,  379,  380,  380,  649,  426,  275,  461,  461,  273,
      426,  646,  276,  526,  526,  313,  645,  540,  277,  644,
      643,  642,  380,  641,  461,  640,  377,  540,  379,  540,
      540,  540,  639,  638,  637,  636,  634,  632,  631,  630,
      629,  628,  627,  626,  625,  623,  622,  526,  672,  672,
      672,  673,  673,  674,  674,  674,  675,  675,  676,  676,

      621,  616,  612,  611,  610,  609,  608,  607,  606,  605,
      603,  599,  596,  595,  593,  592,  591,  590,  589,  588,
      587,  586,  584,  583,  582,  581,  580,  579,  577,  576,
      571,  570,  568,  567,  566,  565,  563,  562,  561,  560,
      556,  555,  554,  553,  551,  550,  549,  547,  546,  544,
      542,  539,  538,  537,  534,  533,  532,  531,  530,  529,
      528,  527,  524,  523,  520,  518,  515,  513,  512,  511,
      508,  507,  506,  505,  504,  503,  501,  500,  499,  498,
      497,  495,  493,  492,  487,  485,  484,  483,  482,  480,
      478,  476,  475,  474,  473,  472,  470,  469,  468,  467,

      466,  465,  464,  460,  458,  457,  456,  454,  453,  452,
      451,  449,  448,  446,  445,  443,  442,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  428,  427,
      425,  423,  422,  421,  420,  419,  417,  416,  415,  414,
      412,  411,  408,  407,  406,  404,  403,  402,  401,  400,
      399,  398,  396,  395,  394,  392,  391,  390,  389,  387,
      386,  385,  384,  383,  382,  378,  374,  373,  372,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      358,  357,  356,  355,  354,  352,  351,  350,  349,  348,
      347,  345,  344,  343,  342,  341,  340,  338,  337,  336,

      335,  334,  333,  329,  328,  327,  326,  325,  324,  322,
      321,  320,  319,  318,  317,  316,  315,  312,  310,  309,
      308,  305,  304,  303,  301,  300,  298,  296,  295,  294,
      293,  292,  291,  289,  288,  287,  286,  285,  283,  282,
      281,  280,  279,  274,  271,  270,  269,  268,  267,  266,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  235,  234,  233,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,

      211,  210,  209,  208,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  154,  153,
      150,  149,  148,  147,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  134,  133,  132,  130,  129,  127,  126,
      124,  123,  122,  121,  120,  119,  118,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   93,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   82,   81,   80,   79,

       78,   76,   75,   74,   73,   72,   71,   69,   59,   49,
       48,   30,   26,   25,   21,   18,   15,   14,   12,   11,
       10,    9,    5,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671,  671,  671,
      671,  671,  671,  671,  671,  671,  671,  671
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
/*	SCCS Id: @(#)lev_lex.c	3.4	2000/12/22	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 *
	 * Digital UNIX is difficult and still has int in spite of all
	 * other signs.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT) && defined(POSIX_TYPES)
#  if !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# if defined(VOIDYYPUT) && defined(__osf__)
#  undef VOIDYYPUT
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

/*
 *	This is a hack required by Michael Hamel to get things
 *	working on the Mac.
 */
#if defined(MAC_MPW) && !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
#undef input
#undef unput
#define unput(c) { yytchar = (c); if (yytchar == 10) yylineno--; *yysptr++ = yytchar; }
# ifndef YYNEWLINE
# define YYNEWLINE 10
# endif

char
input()		/* Under MPW \n is chr(13)! Compensate for this. */
{
	if (yysptr > yysbuf) return(*--yysptr);
	else {
		yytchar = getc(yyin);
		if (yytchar == '\n') {
		    yylineno++;
		    return(YYNEWLINE);
		}
		if (yytchar == EOF) return(0);
		else		    return(yytchar);
	}
}
#endif	/* MAC_MPW && !FLEX_SCANNER && !FLEXHACK_SCANNER */

#define MAPC 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 672 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 824 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, yyleng);
		  map_cnt += yyleng;
		  map[map_cnt] = 0;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
return GEOMETRY_ID;
	YY_BREAK
case 12:
YY_RULE_SETUP
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
return OBJFLAGS_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
return COBJECT_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
return MONSTER_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
return TRAP_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
return DOOR_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
return DRAWBRIDGE_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
return MAZEWALK_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
return WALLIFY_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
return REGION_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
return RANDOM_PLACES_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
return ALTAR_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
return LADDER_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
return STAIR_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
return PORTAL_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
return TELEPRT_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
return RANDOMREGION_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
return BRANCH_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
return FOUNTAIN_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
return SINK_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
return POOL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
return NON_DIGGABLE_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
return NON_PASSWALL_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
return ROOM_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
return SUBROOM_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
return RAND_CORRIDOR_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
return CORRIDOR_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
return GOLD_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
return ENGRAVING_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
return NAME_ID;
	YY_BREAK
case 45:
YY_RULE_SETUP
return CHANCE_ID;
	YY_BREAK
case 46:
YY_RULE_SETUP
return LEV;
	YY_BREAK
case 47:
YY_RULE_SETUP
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
return O_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
return M_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
return P_REGISTER;
	YY_BREAK
case 61:
YY_RULE_SETUP
return A_REGISTER;
	YY_BREAK
case 62:
YY_RULE_SETUP
return R_REGISTER;
	YY_BREAK
case 63:
YY_RULE_SETUP
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_CO; return ALIGNMENT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_NONCO; return ALIGNMENT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ yylval.i=ENGR_BLOOD; return ENGRAVING_TYPE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ return CONTAINED; }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ yylval.i=OBJF_LIT; return OBJFLAG_TYPE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ yylval.i=OBJF_BURIED; return OBJFLAG_TYPE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
{ yylval.i=ARBOREAL; return FLAG_TYPE; }	/* KMH */
	YY_BREAK
case 109:
YY_RULE_SETUP
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
{ yylval.i=SPOOKY; return FLAG_TYPE; }
	YY_BREAK
case 111:
YY_RULE_SETUP
{ yylval.i=LETHE; return FLAG_TYPE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 114:
YY_RULE_SETUP
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 115:
YY_RULE_SETUP
{ line_number++; }
	YY_BREAK
case 116:
YY_RULE_SETUP
;
	YY_BREAK
case 117:
YY_RULE_SETUP
{ yylval.i = yytext[2]; return CHAR; }
	YY_BREAK
case 118:
YY_RULE_SETUP
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 119:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case 120:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 672 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 672 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 671);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l*/
