/*    SCCS Id: @(#)winami.p	3.1 93/01/08			 */
/*    Copyright (c) Gregg Wonderly, Naperville, IL, 1992, 1993	 */
/* NetHack may be freely redistributed. See license for details. */
/* winami.c */
void amii_raw_print(const char *);
void amii_raw_print_bold(const char *);
void amii_start_menu(winid );
void amii_add_menu(winid  , char  , int  , const char *);
void amii_end_menu(winid  , char  , const char * , const char *);
char amii_select_menu(winid );
void NDECL(amii_update_inventory );
void NDECL(amii_mark_synch );
void NDECL(amii_wait_synch );
void NDECL(amii_setclipped );
void amii_cliparound(int  , int );
void NDECL(amii_askname );
void NDECL(amii_player_selection );
void NDECL(flush_output );
void amii_destroy_nhwindow(winid );
int amii_create_nhwindow(int );
void NDECL(amii_init_nhwindows );
int NDECL(amii_get_ext_cmd);
char amii_yn_function(const char * , const char * , char );
void amii_addtopl(const char *);
void TextSpaces(struct RastPort * , int );
void amii_putstr(winid  , int  , const char *);
void amii_putsym(winid  , int  , int  , CHAR_P );
void amii_clear_nhwindow(winid );
void amii_exit_nhwindows(const char *);
int amii_nh_poskey(int * , int * , int *);
int NDECL(amii_nhgetch );
void NDECL(amii_get_nh_event );
void NDECL(amii_remember_topl );
int NDECL(amii_doprev_message );
void amii_display_nhwindow(winid  , boolean );
void amii_display_file(const char * , boolean );
void amii_curs(winid  , int  , int );
void amii_print_glyph(winid  , xchar  , xchar  , int );
void DoMenuScroll(int  , int );
void DisplayData(int  , int  , int );
void SetPropInfo(struct Window * , struct Gadget * , long  , long  , long );
void kill_nhwindows(int );
void amii_cl_end(struct amii_WinDesc * , int );
void cursor_off(winid );
void cursor_on(winid );
void NDECL(amii_getret );
void amii_getlin(const char * , char *);
void getlind(const char * , char * , const char *);
void amii_suspend_nhwindows(char * );
void NDECL(amii_resume_nhwindows);
void NDECL(amii_bell);
void NDECL(EditColor);
void DrawCol(struct Window *, int, UWORD * );
void DispCol(struct Window *w, int idx, UWORD * );
void SetBorder(struct Gadget *);
void NDECL( port_help );
void dismiss_nhwindow(winid);
