#	NetHack Makefile.
#	SCCS Id: @(#)Makefile.dat	3.4	1992/09/18

# for Atari
# SHELL=E:/GEMINI2/MUPFEL.TTP
# UUDECODE=uudecode

VARDAT = data rumors quest.dat oracles options

all:	$(VARDAT) spec_levs dungeon dungeon2 dungeon3 dungeon4 dungeon5 dungeon6 dungeon7 dungeon8

../util/makedefs:
	(cd ../util ; make makedefs)

../util/dgn_comp:
	(cd ../util ; make dgn_comp)

../util/lev_comp:
	(cd ../util ; make lev_comp)

../util/tile2x11:
	(cd ../util ; make tile2x11)

../util/tile2beos:
	(cd ../util ; make tile2beos)

../util/tile2png:
	(cd ../util ; make tile2png)

../util/magtile:
	(cd ../util ; make magtile)

../util/bigtile:
	(cd ../util ; make bigtile)

../util/txtmerge:
	(cd ../util ; make txtmerge)

../util/txtbg:
	(cd ../util ; make txtbg)

../util/mapmerge:
	(cd ../util ; make mapmerge)

../util/tile2bmp:
	(cd ../util ; make tile2bmp)

x11tiles: ../util/tile2x11 ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt
	../util/tile2x11 ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt

x11tiles.map: ../util/mapmerge ../win/share/monsters.map \
				../win/share/objects.map ../win/share/other.map
	../util/mapmerge x11tiles.map ../win/share/monsters.map \
				../win/share/objects.map ../win/share/other.map

x11bigtiles:	../util/tile2x11 ../win/share/mon32.txt \
		../win/share/obj32.txt ../win/share/oth32.txt
	../util/tile2x11 -o x11bigtiles ../win/share/mon32.txt \
		../win/share/obj32.txt ../win/share/oth32.txt

x11bigtiles.map:	x11tiles.map
	cp x11tiles.map x11bigtiles.map

x11big3dtiles:	../util/tile2x11 ../win/share/mon3d.txt \
		../win/share/obj3d.txt ../win/share/oth3d.txt
	../util/tile2x11 -o x11big3dtiles ../win/share/mon3d.txt \
		../win/share/obj3d.txt ../win/share/oth3d.txt

x11big3dtiles.map:	x11tiles.map
	cp x11tiles.map x11big3dtiles.map

beostiles: ../util/tile2beos ../win/share/monsters.txt ../win/share/objects.txt \
			../win/share/other.txt
	../util/tile2beos ../win/share/monsters.txt ../win/share/objects.txt \
			../win/share/other.txt

gltile16.png: ../util/tile2png ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt
	../util/tile2png -o $@ ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt

gltile16.map: ../util/mapmerge ../win/share/monsters.map \
				../win/share/objects.map ../win/share/other.map
	../util/mapmerge gltile16.map ../win/share/monsters.map \
				../win/share/objects.map ../win/share/other.map

gltile32.png:	../util/tile2png ../win/share/mon32.txt \
		../win/share/obj32.txt ../win/share/oth32.txt
	../util/tile2png -o $@ -t ../win/share/mon32.txt \
		../win/share/obj32.txt ../win/share/oth32.txt

gltile32.map:	gltile16.map
	cp gltile16.map gltile32.map

gltile64.png:	../util/tile2png ../win/share/mon3d.txt \
		../win/share/obj3d.txt ../win/share/oth3d.txt
	../util/tile2png -o $@ -t ../win/share/mon3d.txt \
		../win/share/obj3d.txt ../win/share/oth3d.txt

gltile64.map:	gltile16.map
	cp gltile16.map gltile64.map

glfont8.png:	../util/tile2png ../win/gl/font8.txt
	../util/tile2png -o $@ -f ../win/gl/font8.txt

glfont14.png:	../util/tile2png ../win/gl/font14.txt
	../util/tile2png -o $@ -f ../win/gl/font14.txt

glfont20.png:	../util/tile2png ../win/gl/font20.txt
	../util/tile2png -o $@ -f ../win/gl/font20.txt

glfont22.png:	../util/tile2png ../win/gl/font22.txt
	../util/tile2png -o $@ -f ../win/gl/font22.txt

gllogo.png:	../util/tile2png ../win/gl/logo.txt
	../util/tile2png -o $@ -a 28 ../win/gl/logo.txt

glrip.png:	../util/tile2png ../win/gl/rip.txt
	../util/tile2png -o $@ -a 20 ../win/gl/rip.txt

../win/share/monmag.txt:	../util/magtile ../win/share/monsters.txt
	../util/magtile

../win/share/objmag.txt:	../util/magtile ../win/share/objects.txt
	../util/magtile

../win/share/othmag.txt:	../util/magtile ../win/share/other.txt
	../util/magtile

../win/share/monbig.txt:	../util/bigtile ../win/share/mon32-t.txt \
				../win/share/obj32-t.txt \
				../win/share/oth32-t.txt
	../util/bigtile

../win/share/objbig.txt:	../util/bigtile ../win/share/mon32-t.txt \
				../win/share/obj32-t.txt \
				../win/share/oth32-t.txt
	../util/bigtile

../win/share/othbig.txt:	../util/bigtile ../win/share/mon32-t.txt \
				../win/share/obj32-t.txt \
				../win/share/oth32-t.txt
	../util/bigtile

../win/share/mon32.txt:	../util/txtbg ../win/share/mon32-t.txt
	../util/txtbg ../win/share/mon32-t.txt ../win/share/mon32.txt

../win/share/obj32.txt:	../util/txtbg ../win/share/obj32-t.txt
	../util/txtbg ../win/share/obj32-t.txt ../win/share/obj32.txt

../win/share/oth32.txt:	../util/txtbg ../win/share/oth32-t.txt
	../util/txtbg ../win/share/oth32-t.txt ../win/share/oth32.txt

../win/share/mon32-t.txt:	../util/txtmerge ../win/share/monmag.txt \
		../win/share/mon32mi.txt ../win/share/mon32alg.txt \
		../win/share/mon32aw.txt ../win/share/mon32se.txt \
		../win/share/palette.txt
	../util/txtmerge -p ../win/share/palette.txt ../win/share/mon32-t.txt \
		../win/share/monmag.txt -b ../win/share/mon32mi.txt \
		-b ../win/share/mon32se.txt -bff00ff ../win/share/mon32alg.txt \
		-bff00ff ../win/share/mon32aw.txt 

../win/share/obj32-t.txt:	../util/txtmerge ../win/share/objmag.txt \
		../win/share/obj32mi.txt ../win/share/obj32se.txt \
		../win/share/obj32alg.txt ../win/share/palette.txt
	../util/txtmerge -p ../win/share/palette.txt ../win/share/obj32-t.txt \
		../win/share/objmag.txt -b ../win/share/obj32mi.txt \
		-b ../win/share/obj32se.txt -bff00ff ../win/share/obj32alg.txt

../win/share/oth32-t.txt:	../util/txtmerge ../win/share/othmag.txt \
		../win/share/oth32mi.txt ../win/share/oth32se.txt \
		../win/share/oth32alg.txt ../win/share/palette.txt
	../util/txtmerge -p ../win/share/palette.txt ../win/share/oth32-t.txt \
		../win/share/othmag.txt -b ../win/share/oth32mi.txt \
		-b ../win/share/oth32se.txt -bff00ff ../win/share/oth32alg.txt

../win/share/mon3d.txt:	../util/txtmerge ../win/share/monbig.txt \
		../win/share/mon3dmi.txt ../win/share/palette.txt
	../util/txtmerge -p ../win/share/palette.txt ../win/share/mon3d.txt \
		../win/share/monbig.txt -b ../win/share/mon3dmi.txt

../win/share/obj3d.txt:	../util/txtmerge ../win/share/objbig.txt
	cp ../win/share/objbig.txt ../win/share/obj3d.txt

../win/share/oth3d.txt:	../util/txtmerge ../win/share/othbig.txt \
		../win/share/oth3dmi.txt ../win/share/oth-2kmi.txt \
		../win/share/oth3dse.txt ../win/share/palette.txt
	../util/txtmerge -p ../win/share/palette.txt ../win/share/oth3d.txt \
		../win/share/othbig.txt -b ../win/share/oth3dmi.txt \
		-b ../win/share/oth-2kmi.txt -b ../win/share/oth3dse.txt

nhtiles.bmp: ../util/tile2bmp ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt
	../util/tile2bmp $@ ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt

SlashEM.ad: ../win/X11/SlashEM.ad
	cp ../win/X11/SlashEM.ad SlashEM.ad

pet_mark.xbm: ../win/X11/pet_mark.xbm
	cp ../win/X11/pet_mark.xbm pet_mark.xbm

rip.xpm: ../win/X11/rip.xpm
	cp ../win/X11/rip.xpm rip.xpm

mapbg.xpm: ../win/gnome/mapbg.xpm
	cp ../win/gnome/mapbg.xpm mapbg.xpm

nhsplash.xpm: ../win/Qt/nhsplash.xpm
	cp ../win/Qt/nhsplash.xpm nhsplash.xpm

nethack.icns: ../win/Qt/nhicns.uu
	$(UUDECODE) ../win/Qt/nhicns.uu

Info.plist: ../win/Qt/Info.pli
	cp ../win/Qt/Info.pli Info.plist

../util/tile2img.ttp:
	(cd ../util ; make tile2img.ttp)

../util/xpm2img.ttp:
	(cd ../util ; make xpm2img.ttp)
nh16.img: ../util/tile2img.ttp ../win/share/monsters.txt \
                              ../win/share/objects.txt ../win/share/other.txt
	../util/tile2img.ttp nh16.img

rip.img: ../util/xpm2img.ttp
	../util/xpm2img.ttp ../win/X11/rip.xpm rip.img
title.img:
	# cp ../win/gem/title.img title.img
	$(UUDECODE) ../win/gem/title.uu

GEM_RSC.RSC:
	# cp ../win/gem/GEM_RSC.RSC GEM_RSC.RSC
	$(UUDECODE) ../win/gem/gem_rsc.uu

data:	data.base ../util/makedefs
	../util/makedefs -d

rumors:	rumors.tru rumors.fal ../util/makedefs
	../util/makedefs -r

quest.dat:	quest.txt ../util/makedefs
	../util/makedefs -q

oracles:	oracles.txt ../util/makedefs
	../util/makedefs -h

# note: 'options' should have already been made when include/date.h was created
options:	../util/makedefs
	../util/makedefs -v


spec_levs: ../util/lev_comp \
	beholder.des bigroom.des blkmar.des castle.des compu.des	\
	dragons.des endgame.des exmall.des forge.des frnknstn.des	\
	gehennom.des giants.des grund.des guild.des heck.des		\
	hellma.des hitch.des intpla.des key.des knox.des kobold-1.des	\
	kobold-2.des lich.des mall-1.des mall-2.des mall-3.des		\
	medusa.des mines.des mtemple.des newmall.des nightmar.des	\
	nymph.des oracle.des rats.des rndmaze.des rndmazea.des		\
	sea.des sheol.des sokoban.des spiders.des stor-1.des		\
	stor-2.des stor-3.des tomb.des tower.des town.des unheck.des	\
	yendor.des ghbigrm.des gehenX.des kwests.des mazes.des levgn.des	\
	levgx.des emptbgr.des
	../util/lev_comp beholder.des
	../util/lev_comp bigroom.des
	../util/lev_comp blkmar.des
	../util/lev_comp castle.des
	../util/lev_comp compu.des
	../util/lev_comp dragons.des
	../util/lev_comp endgame.des
	../util/lev_comp exmall.des
	../util/lev_comp forge.des
	../util/lev_comp frnknstn.des
	../util/lev_comp gehennom.des
	../util/lev_comp gehenX.des
	../util/lev_comp giants.des
	../util/lev_comp grund.des
	../util/lev_comp guild.des
	../util/lev_comp heck.des
	../util/lev_comp hellma.des
	../util/lev_comp hitch.des
	../util/lev_comp intpla.des
	../util/lev_comp key.des
	../util/lev_comp knox.des
	../util/lev_comp kobold-1.des
	../util/lev_comp kobold-2.des
	../util/lev_comp kwests.des
	../util/lev_comp lich.des
	../util/lev_comp mall-1.des
	../util/lev_comp mall-2.des
	../util/lev_comp mall-3.des
	../util/lev_comp medusa.des
	../util/lev_comp mines.des
	../util/lev_comp mtemple.des
	../util/lev_comp newmall.des
	../util/lev_comp nightmar.des
	../util/lev_comp nymph.des
	../util/lev_comp oracle.des
	../util/lev_comp rats.des
	../util/lev_comp rndmaze.des
	../util/lev_comp rndmazea.des
	../util/lev_comp sea.des
	../util/lev_comp sheol.des
	../util/lev_comp sokoban.des
	../util/lev_comp spiders.des
	../util/lev_comp stor-1.des
	../util/lev_comp stor-2.des
	../util/lev_comp stor-3.des
	../util/lev_comp tomb.des
	../util/lev_comp tower.des
	../util/lev_comp town.des
	../util/lev_comp unheck.des
	../util/lev_comp yendor.des
	../util/lev_comp ghbigrm.des
	../util/lev_comp mazes.des
	../util/lev_comp levgn.des
	../util/lev_comp levgx.des
	../util/lev_comp emptbgr.des
	../util/lev_comp \
	Abuser.des Acid.des Act.des Altmer.des Amazon.des Arch.des	\
	Artist.des Assassin.des Augurer.des Barb.des Bard.des		\
	Dwarf.des Dopp.des Gnome.des Hobbit.des Darkelf.des		\
	Binder.des Bleeder.des Bloodsee.des Bosmer.des Bully.des	\
	Caveman.des Cheval.des Convict.des Cook.des Courier.des		\
	Cyborg.des Deatheat.des Diver.des Doll.des Drunk.des		\
	Dunmer.des Electric.des Elf.des Elfreal.des Firef.des		\
	Flame.des Foxhound.des Gamer.des Gangster.des Geek.des		\
	Gladia.des Goff.des Gradu.des Gunner.des Healer.des Ice.des	\
	Jedi.des Jester.des Knight.des Korsair.des Ladies.des		\
	Libra.des Locks.des Lunatic.des Mahou.des Monk.des Music.des	\
	Mystic.des Necro.des Ninja.des Noble.des Offic.des		\
	Ordinat.des Otaku.des Paladin.des Pickpock.des Pirate.des	\
	Polit.des Priest.des Psion.des Ranger.des Rocker.des		\
	Rogue.des Sage.des Saiyan.des Samurai.des Scient.des		\
	Scribe.des Slavemas.des Slayer.des Spacew.des Stunt.des		\
	Supermar.des Thalmor.des Top.des Tourist.des Trans.des		\
	Under.des Valkyrie.des Wandkeep.des Warrior.des Wizard.des	\
	Yeoman.des Zooke.des Murderer.des Failed.des Camper.des	\
	Suser.des Sexy.des Justice.des Fencer.des Fighter.des	\
	Slime.des Erdrick.des Anachr.des Druid.des Marine.des \
	Occult.des Element.des Chaos.des Wildtal.des \
	Medium.des Poison.des Transs.des Unbel.des Kurwa.des Prost.des \
	Form.des Feminist.des Tracer.des Nuclear.des Scholar.des \
	Acu.des Hussy.des Mason.des Demago.des Cellar.des Grenad.des \
	Social.des Walsch.des Cyber.des Dissi.des Astro.des Crack.des \
	Janit.des Smarin.des Yautja.des Xelnaga.des Weirdboy.des \
	Stormboy.des Empath.des Psyker.des Software.des Quarter.des \
	Mastermi.des Tosser.des Symbia.des Pract.des Millsw.des \
	Gender.des Fjorde.des Emera.des Combat.des Aklyst.des \
	Drag.des Carto.des

	../util/lev_comp Abuser.des
	../util/lev_comp Acid.des
	../util/lev_comp Act.des
	../util/lev_comp Altmer.des
	../util/lev_comp Amazon.des
	../util/lev_comp Druid.des
	../util/lev_comp Anachr.des
	../util/lev_comp Arch.des
	../util/lev_comp Artist.des
	../util/lev_comp Assassin.des
	../util/lev_comp Augurer.des
	../util/lev_comp Dwarf.des
	../util/lev_comp Dopp.des
	../util/lev_comp Darkelf.des
	../util/lev_comp Hobbit.des
	../util/lev_comp Gnome.des
	../util/lev_comp Barb.des
	../util/lev_comp Demago.des
	../util/lev_comp Cellar.des
	../util/lev_comp Grenad.des
	../util/lev_comp Social.des
	../util/lev_comp Walsch.des
	../util/lev_comp Bard.des
	../util/lev_comp Binder.des
	../util/lev_comp Acu.des
	../util/lev_comp Mason.des
	../util/lev_comp Hussy.des
	../util/lev_comp Bleeder.des
	../util/lev_comp Bloodsee.des
	../util/lev_comp Bosmer.des
	../util/lev_comp Bully.des
	../util/lev_comp Camper.des
	../util/lev_comp Caveman.des
	../util/lev_comp Cheval.des
	../util/lev_comp Convict.des
	../util/lev_comp Cook.des
	../util/lev_comp Courier.des
	../util/lev_comp Cyborg.des
	../util/lev_comp Deatheat.des
	../util/lev_comp Diver.des
	../util/lev_comp Doll.des
	../util/lev_comp Drunk.des
	../util/lev_comp Dunmer.des
	../util/lev_comp Electric.des
	../util/lev_comp Poison.des
	../util/lev_comp Occult.des
	../util/lev_comp Element.des
	../util/lev_comp Chaos.des
	../util/lev_comp Wildtal.des
	../util/lev_comp Form.des
	../util/lev_comp Feminist.des
	../util/lev_comp Tracer.des
	../util/lev_comp Nuclear.des
	../util/lev_comp Scholar.des
	../util/lev_comp Kurwa.des
	../util/lev_comp Prost.des
	../util/lev_comp Elf.des
	../util/lev_comp Elfreal.des
	../util/lev_comp Erdrick.des
	../util/lev_comp Failed.des
	../util/lev_comp Firef.des
	../util/lev_comp Flame.des
	../util/lev_comp Foxhound.des
	../util/lev_comp Gamer.des
	../util/lev_comp Gangster.des
	../util/lev_comp Geek.des
	../util/lev_comp Gladia.des
	../util/lev_comp Goff.des
	../util/lev_comp Gradu.des
	../util/lev_comp Gunner.des
	../util/lev_comp Marine.des
	../util/lev_comp Healer.des
	../util/lev_comp Ice.des
	../util/lev_comp Jedi.des
	../util/lev_comp Jester.des
	../util/lev_comp Knight.des
	../util/lev_comp Korsair.des
	../util/lev_comp Ladies.des
	../util/lev_comp Suser.des
	../util/lev_comp Sexy.des
	../util/lev_comp Medium.des
	../util/lev_comp Justice.des
	../util/lev_comp Fighter.des
	../util/lev_comp Fencer.des
	../util/lev_comp Libra.des
	../util/lev_comp Locks.des
	../util/lev_comp Lunatic.des
	../util/lev_comp Mahou.des
	../util/lev_comp Monk.des
	../util/lev_comp Murderer.des
	../util/lev_comp Music.des
	../util/lev_comp Mystic.des
	../util/lev_comp Necro.des
	../util/lev_comp Ninja.des
	../util/lev_comp Noble.des
	../util/lev_comp Offic.des
	../util/lev_comp Ordinat.des
	../util/lev_comp Otaku.des
	../util/lev_comp Paladin.des
	../util/lev_comp Pickpock.des
	../util/lev_comp Pirate.des
	../util/lev_comp Polit.des
	../util/lev_comp Priest.des
	../util/lev_comp Psion.des
	../util/lev_comp Ranger.des
	../util/lev_comp Rocker.des
	../util/lev_comp Rogue.des
	../util/lev_comp Sage.des
	../util/lev_comp Saiyan.des
	../util/lev_comp Samurai.des
	../util/lev_comp Scient.des
	../util/lev_comp Scribe.des
	../util/lev_comp Slavemas.des
	../util/lev_comp Slayer.des
	../util/lev_comp Slime.des
	../util/lev_comp Spacew.des
	../util/lev_comp Stunt.des
	../util/lev_comp Cyber.des
	../util/lev_comp Dissi.des
	../util/lev_comp Astro.des
	../util/lev_comp Crack.des
	../util/lev_comp Janit.des
	../util/lev_comp Smarin.des
	../util/lev_comp Yautja.des
	../util/lev_comp Xelnaga.des
	../util/lev_comp Weirdboy.des
	../util/lev_comp Stormboy.des
	../util/lev_comp Empath.des
	../util/lev_comp Psyker.des
	../util/lev_comp Software.des
	../util/lev_comp Quarter.des
	../util/lev_comp Mastermi.des
	../util/lev_comp Tosser.des
	../util/lev_comp Symbia.des
	../util/lev_comp Pract.des
	../util/lev_comp Millsw.des
	../util/lev_comp Gender.des
	../util/lev_comp Fjorde.des
	../util/lev_comp Emera.des
	../util/lev_comp Combat.des
	../util/lev_comp Aklyst.des
	../util/lev_comp Drag.des
	../util/lev_comp Carto.des
	../util/lev_comp Supermar.des
	../util/lev_comp Thalmor.des
	../util/lev_comp Top.des
	@if egrep -s tourists options > /dev/null ; then \
	echo ../util/lev_comp Tourist.des ; ../util/lev_comp Tourist.des ; \
	else rm -f Tou-goal.lev Tou-fil?.lev Tou-loca.lev Tou-strt.lev ; fi
	../util/lev_comp Trans.des
	../util/lev_comp Transs.des
	../util/lev_comp Unbel.des
	../util/lev_comp Under.des
	../util/lev_comp Valkyrie.des
	../util/lev_comp Wandkeep.des
	../util/lev_comp Warrior.des
	../util/lev_comp Wizard.des
	@if egrep -s yeomen options > /dev/null ; then \
	echo ../util/lev_comp Yeoman.des ; ../util/lev_comp Yeoman.des ; \
	else rm -f Yeo-goal.lev Yeo-fil?.lev Yeo-loca.lev Yeo-strt.lev ; fi
	../util/lev_comp Zooke.des
	touch spec_levs

dungeon: dungeon.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon.pdf
dungeon2: dungeon2.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon2.pdf
dungeon3: dungeon3.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon3.pdf
dungeon4: dungeon4.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon4.pdf
dungeon5: dungeon5.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon5.pdf
dungeon6: dungeon6.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon6.pdf
dungeon7: dungeon7.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon7.pdf
dungeon8: dungeon8.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon8.pdf

spotless:
	-rm -f spec_levs *.lev $(VARDAT) dungeon dungeon2 dungeon3 dungeon4 dungeon.pdf dungeon2.pdf dungeon3.pdf dungeon4.pdf
	-rm -f dungeon5 dungeon6 dungeon7 dungeon8 dungeon5.pdf dungeon6.pdf dungeon7.pdf dungeon8.pdf
	-rm -f nhshare nhushare x11tiles x11bigtiles x11big3dtiles beostiles
	-rm -f x11tiles.map x11bigtiles.map x11big3dtiles.map
	-rm -f gtkrc
	-rm -f gl*.png
	-rm -f pet_mark.xbm rip.xpm mapbg.xpm
	-rm -f rip.img GEM_RSC.RSC title.img nh16.img SlashEM.ad
	-rm -f ../win/share/monmag.txt ../win/share/mon32.txt
	-rm -f ../win/share/objmag.txt ../win/share/obj32.txt
	-rm -f ../win/share/othmag.txt ../win/share/oth32.txt
	-rm -f ../win/share/monbig.txt ../win/share/mon3d.txt
	-rm -f ../win/share/objbig.txt ../win/share/obj3d.txt
	-rm -f ../win/share/othbig.txt ../win/share/oth3d.txt
	-rm -f ../win/share/mon32-t.txt
	-rm -f ../win/share/obj32-t.txt
	-rm -f ../win/share/oth32-t.txt
