/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Nov 29 22:20:51 2018"
#define BUILD_TIME (1543526451L)

#define VERSION_NUMBER 0x02040200UL
#define VERSION_FEATURES 0x000fee46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x5d3cda40UL
#define VERSION_SANITY2 0x6cf3efc4UL

#define VERSION_STRING "2.4.2"
#define VERSION_ID \
 "Windows SlashEMExtended tty Version 2.4.2 - last build Thu Nov 29 22:20:51 2018."
