/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue Aug 22 09:55:39 2023"
#define BUILD_TIME (1692694539L)

#define VERSION_NUMBER 0x02080600UL
#define VERSION_FEATURES 0x000fee46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0xcfd6bb30UL
#define VERSION_SANITY2 0xd4f5c6acUL

#define VERSION_STRING "2.8.6"
#define VERSION_ID \
 "Windows SlashEMExtended tty Version 2.8.6 - last build Tue Aug 22 09:55:39 2023."
