/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Apr 23 23:26:38 2020"
#define BUILD_TIME (1587677198L)

#define VERSION_NUMBER 0x02060600UL
#define VERSION_FEATURES 0x000fee46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x316fe1ccUL
#define VERSION_SANITY2 0xb0f53b50UL

#define VERSION_STRING "2.6.6"
#define VERSION_ID \
 "Windows SlashEMExtended tty Version 2.6.6 - last build Thu Apr 23 23:26:38 2020."
