/*	SCCS Id: @(#)trap.h	3.4	2000/08/30	*/
/* Copyright (c) Stichting Mathematisch Centrum, Amsterdam, 1985. */
/* NetHack may be freely redistributed.  See license for details. */

/* note for 3.1.0 and later: no longer manipulated by 'makedefs' */

#ifndef TRAP_H
#define TRAP_H

union vlaunchinfo {
	short v_launch_otyp;	/* type of object to be triggered */
	coord v_launch2;	/* secondary launch point (for boulders) */
};

struct trap {
	struct trap *ntrap;
	xchar tx,ty;
	d_level dst;	/* destination for portals */
	coord launch;
	int ttyp; /* are you kidding me? You only make room for 32 traps? That's not nearly enough for me! --Amy */
	int trapdiff; /* difficulty - this affects your chance of finding it via search command */
	Bitfield(tseen,1);
	Bitfield(hiddentrap,1); /* invisible, and I mean really invisible, even if you have see invis --Amy */
	Bitfield(giveshp,1); /* untrapping it may give +maxHP --Amy */
	Bitfield(once,1);
	Bitfield(artionce,1); /* so that you cannot exploit artifacts like Ka-Blammo --Amy */
	Bitfield(tdetected,1); /* so things like map amnesia don't allow you to farm searching skill --Amy */
	Bitfield(madeby_u,1); /* So monsters may take offence when you trap
				 them.	Recognizing who made the trap isn't
				 completely unreasonable, everybody has
				 their own style.  This flag is also needed
				 when you untrap a monster.  It would be too
				 easy to make a monster peaceful if you could
				 set a trap for it and then untrap it. */
	union vlaunchinfo vl;
#define launch_otyp	vl.v_launch_otyp
#define launch2		vl.v_launch2
};

extern struct trap *ftrap;
#define newtrap()	(struct trap *) alloc(sizeof(struct trap))
#define dealloc_trap(trap) free((void *) (trap))

/* reasons for statue animation */
#define ANIMATE_NORMAL	0
#define ANIMATE_SHATTER 1
#define ANIMATE_SPELL	2

/* reasons for animate_statue's failure */
#define AS_OK		 0	/* didn't fail */
#define AS_NO_MON	 1	/* makemon failed */
#define AS_MON_IS_UNIQUE 2	/* statue monster is unique */

/* Note: if adding/removing a trap, adjust trap_engravings[] in mklev.c */

/* unconditional traps */
#define NO_TRAP		0
#define ARROW_TRAP	1
#define DART_TRAP	2
#define ROCKTRAP	3
#define SQKY_BOARD	4
#define BEAR_TRAP	5
#define LANDMINE	6
#define ROLLING_BOULDER_TRAP	7
#define SLP_GAS_TRAP	8
#define RUST_TRAP	9
#define FIRE_TRAP	10
#define PIT		11
#define SPIKED_PIT	12
#define HOLE		13
#define TRAPDOOR	14
#define TELEP_TRAP	15
#define LEVEL_TELEP	16
#define MAGIC_PORTAL	17
#define WEB		18
#define STATUE_TRAP	19
#define MAGIC_TRAP	20
#define ANTI_MAGIC	21
#define POLY_TRAP	22
#define ICE_TRAP	23
#define SPEAR_TRAP	24
#define COLLAPSE_TRAP	25
#define MAGIC_BEAM_TRAP	26
#define SHIT_TRAP	27
#define ANIMATION_TRAP	28
#define GLYPH_OF_WARDING	29
#define SCYTHING_BLADE	30
#define BOLT_TRAP	31
#define ACID_POOL	32
#define WATER_POOL	33
#define POISON_GAS_TRAP	34
#define SLOW_GAS_TRAP	35
#define SHOCK_TRAP	36
#define RMB_LOSS_TRAP		37
#define DISPLAY_TRAP		38
#define SPELL_LOSS_TRAP		39
#define YELLOW_SPELL_TRAP		40
#define AUTO_DESTRUCT_TRAP		41
#define MEMORY_TRAP		42
#define INVENTORY_TRAP		43
#define BLACK_NG_WALL_TRAP		44
#define MENU_TRAP		45
#define SPEED_TRAP		46
#define SUPERSCROLLER_TRAP		47
#define ACTIVE_SUPERSCROLLER_TRAP		48
#define SWARM_TRAP		49
#define AUTOMATIC_SWITCHER		50
#define UNKNOWN_TRAP		51
#define HEEL_TRAP		52
#define VULN_TRAP		53
#define LAVA_TRAP		54
#define FLOOD_TRAP		55
#define DRAIN_TRAP		56
#define FREE_HAND_TRAP		57
#define DISINTEGRATION_TRAP		58
#define UNIDENTIFY_TRAP		59
#define THIRST_TRAP		60
#define LUCK_TRAP		61
#define SHADES_OF_GREY_TRAP		62
#define ITEM_TELEP_TRAP		63
#define GRAVITY_TRAP		64
#define DEATH_TRAP		65
#define STONE_TO_FLESH_TRAP		66
#define QUICKSAND_TRAP		67
#define FAINT_TRAP		68
#define CURSE_TRAP		69
#define DIFFICULTY_TRAP		70
#define SOUND_TRAP		71
#define CASTER_TRAP		72
#define WEAKNESS_TRAP		73
#define ROT_THIRTEEN_TRAP		74
#define BISHOP_TRAP		75
#define CONFUSION_TRAP		76
#define NUPESELL_TRAP		77
#define DROP_TRAP		78
#define DSTW_TRAP		79
#define STATUS_TRAP		80
#define ALIGNMENT_TRAP		81
#define STAIRS_TRAP		82

#define PESTILENCE_TRAP		83
#define FAMINE_TRAP		84
#define RELOCATION_TRAP		85

#define UNINFORMATION_TRAP		86

#define INTRINSIC_LOSS_TRAP	87
#define BLOOD_LOSS_TRAP	88
#define BAD_EFFECT_TRAP	89
#define MULTIPLY_TRAP	90
#define AUTO_VULN_TRAP	91
#define TELE_ITEMS_TRAP	92
#define NASTINESS_TRAP	93

#define RECURSION_TRAP	94
#define RESPAWN_TRAP	95
#define WARP_ZONE	96
#define CAPTCHA_TRAP	97
#define MIND_WIPE_TRAP	98
#define THROWING_STAR_TRAP	99
#define SHIT_PIT	100
#define SHAFT_TRAP	101
#define LOCK_TRAP	102
#define MAGIC_CANCELLATION_TRAP	103
#define FARLOOK_TRAP	104
#define GATEWAY_FROM_HELL	105
#define GROWING_TRAP	106
#define COOLING_TRAP	107
#define BAR_TRAP	108
#define LOCKING_TRAP	109
#define AIR_TRAP	110
#define TERRAIN_TRAP	111

#define LOUDSPEAKER 112
#define NEST_TRAP 113
#define BULLET_TRAP 114
#define PARALYSIS_TRAP 115
#define CYANIDE_TRAP 116
#define LASER_TRAP 117
#define GIANT_CHASM 118
#define FART_TRAP 119
#define CONFUSE_TRAP 120
#define STUN_TRAP 121
#define HALLUCINATION_TRAP 122
#define PETRIFICATION_TRAP 123
#define NUMBNESS_TRAP 124
#define FREEZING_TRAP 125
#define BURNING_TRAP 126
#define FEAR_TRAP 127
#define BLINDNESS_TRAP 128
#define GLIB_TRAP 129
#define SLIME_TRAP 130
#define INERTIA_TRAP 131
#define TIME_TRAP 132
#define LYCANTHROPY_TRAP 133
#define UNLIGHT_TRAP 134
#define ELEMENTAL_TRAP 135
#define ESCALATING_TRAP 136
#define NEGATIVE_TRAP 137
#define MANA_TRAP 138
#define SIN_TRAP 139
#define DESTROY_ARMOR_TRAP 140
#define DIVINE_ANGER_TRAP 141
#define GENETIC_TRAP 142
#define MISSINGNO_TRAP 143
#define CANCELLATION_TRAP 144
#define HOSTILITY_TRAP 145
#define BOSS_TRAP 146
#define WISHING_TRAP 147
#define RECURRING_AMNESIA_TRAP 148
#define BIGSCRIPT_TRAP 149
#define BANK_TRAP 150
#define ONLY_TRAP 151
#define MAP_TRAP 152
#define TECH_TRAP 153
#define DISENCHANT_TRAP 154
#define VERISIERT 155
#define CHAOS_TRAP 156
#define MUTENESS_TRAP 157
#define NTLL_TRAP 158
#define ENGRAVING_TRAP 159
#define MAGIC_DEVICE_TRAP 160
#define BOOK_TRAP 161
#define LEVEL_TRAP 162
#define QUIZ_TRAP 163

#define FALLING_BOULDER_TRAP 164
#define GLASS_ARROW_TRAP 165
#define GLASS_BOLT_TRAP 166
#define OUT_OF_MAGIC_TRAP 167
#define PLASMA_TRAP 168
#define BOMB_TRAP 169
#define EARTHQUAKE_TRAP 170
#define NOISE_TRAP 171
#define GLUE_TRAP 172
#define GUILLOTINE_TRAP 173
#define BISECTION_TRAP 174
#define VOLT_TRAP 175
#define HORDE_TRAP 176
#define IMMOBILITY_TRAP 177
#define GREEN_GLYPH 178
#define BLUE_GLYPH 179
#define YELLOW_GLYPH 180
#define ORANGE_GLYPH 181
#define BLACK_GLYPH 182
#define PURPLE_GLYPH 183

#define METABOLIC_TRAP 184
#define TRAP_OF_NO_RETURN 185
#define EGOTRAP 186
#define FAST_FORWARD_TRAP 187
#define TRAP_OF_ROTTENNESS 188
#define UNSKILLED_TRAP 189
#define LOW_STATS_TRAP 190
#define TRAINING_TRAP 191
#define EXERCISE_TRAP 192
#define FALLING_LOADSTONE_TRAP 193
#define SUMMON_UNDEAD_TRAP 194
#define FALLING_NASTYSTONE_TRAP 195

#define SPINED_BALL_TRAP	196	/*[Sakusha]*/
#define PENDULUM_TRAP	197		/*[Sakusha]*/
#define TURN_TABLE	198		/*[Sakusha]*/
#define SCENT_TRAP	199		/*[Sakusha]*/
#define BANANA_TRAP	200		/*[Sakusha]*/
#define FALLING_TUB_TRAP	201	/*from RJNH*/
#define ALARM		202		/*[Sakusha]*/
#define CALTROPS_TRAP	203		/*[Sakusha]*/
#define BLADE_WIRE	204		/*[Sakusha]*/
#define MAGNET_TRAP	205		/*from RJNH*/
#define SLINGSHOT_TRAP	206		/*[Sakusha]*/
#define CANNON_TRAP	207		/*[Sakusha]*/
#define VENOM_SPRINKLER	208		/*[Sakusha]*/
#define FUMAROLE	209		/*[Sakusha]*/

#define MANA_PIT 210
#define ELEMENTAL_PORTAL 211
#define GIRLINESS_TRAP 212
#define FUMBLING_TRAP 213
#define EGOMONSTER_TRAP 214
#define FLOODING_TRAP 215
#define MONSTER_CUBE 216
#define CURSED_GRAVE 217
#define LIMITATION_TRAP 218
#define WEAK_SIGHT_TRAP 219
#define RANDOM_MESSAGE_TRAP 220

#define DESECRATION_TRAP 221
#define STARVATION_TRAP 222
#define DROPLESS_TRAP 223
#define LOW_EFFECT_TRAP 224
#define INVISIBLE_TRAP 225
#define GHOST_WORLD_TRAP 226
#define DEHYDRATION_TRAP 227
#define HATE_TRAP 228
#define SPACEWARS_TRAP 229
#define TEMPORARY_RECURSION_TRAP 230
#define TOTTER_TRAP 231
#define NONINTRINSICAL_TRAP 232
#define DROPCURSE_TRAP 233
#define NAKEDNESS_TRAP 234
#define ANTILEVEL_TRAP 235
#define VENTILATOR 236
#define STEALER_TRAP 237
#define REBELLION_TRAP 238
#define CRAP_TRAP 239
#define MISFIRE_TRAP 240
#define TRAP_OF_WALLS 241

#define DISCONNECT_TRAP 242
#define INTERFACE_SCREW_TRAP 243
#define DIMNESS_TRAP 244
#define EVIL_ARTIFACT_TRAP 245
#define BOSSFIGHT_TRAP 246
#define ENTIRE_LEVEL_TRAP 247
#define BONES_TRAP 248
#define RODNEY_TRAP 249
#define AUTOCURSE_TRAP 250
#define HIGHLEVEL_TRAP 251
#define SPELL_FORGETTING_TRAP 252
#define SOUND_EFFECT_TRAP 253

#define TRAP_PERCENTS	254

#define NEXUS_TRAP	255
#define LEG_TRAP	256
#define ARTIFACT_JACKPOT_TRAP	257
#define MAP_AMNESIA_TRAP	258
#define SPREADING_TRAP	259
#define ADJACENT_TRAP	260
#define SUPERTHING_TRAP	261
#define CURRENT_SHAFT	262
#define LEVITATION_TRAP	263
#define BOWEL_CRAMPS_TRAP	264
#define UNEQUIPPING_TRAP	265
#define GOOD_ARTIFACT_TRAP	266
#define GENDER_TRAP	267
#define TRAP_OF_OPPOSITE_ALIGNMENT	268
#define SINCOUNT_TRAP	269
#define BEAMER_TRAP	270
#define LEVEL_BEAMER	271
#define PET_TRAP	272
#define PIERCING_BEAM_TRAP	273
#define WRENCHING_TRAP	274
#define TRACKER_TRAP	275
#define NURSE_TRAP	276
#define BACK_TO_START_TRAP	277
#define NEMESIS_TRAP	278
#define STREW_TRAP	279
#define OUTTA_DEPTH_TRAP	280
#define PUNISHMENT_TRAP	281
#define BOON_TRAP	282
#define FOUNTAIN_TRAP	283
#define THRONE_TRAP	284
#define ANOXIC_PIT	285
#define ARABELLA_SPEAKER	286
#define FEMMY_TRAP	287
#define MADELEINE_TRAP	288
#define MARLENA_TRAP	289
#define ANASTASIA_TRAP	290
#define FILLER_TRAP	291
#define TOXIC_VENOM_TRAP	292
#define INSANITY_TRAP	293
#define MADNESS_TRAP	294
#define JESSICA_TRAP	295
#define SOLVEJG_TRAP	296
#define WENDY_TRAP	297
#define KATHARINA_TRAP	298
#define ELENA_TRAP	299
#define THAI_TRAP	300
#define ELIF_TRAP	301
#define NADJA_TRAP	302
#define SANDRA_TRAP	303
#define NATALJE_TRAP	304
#define JEANETTA_TRAP	305
#define YVONNE_TRAP	306
#define MAURAH_TRAP	307

#define LOOTCUT_TRAP	308
#define MONSTER_SPEED_TRAP	309
#define SCALING_TRAP	310
#define ENMITY_TRAP	311
#define WHITE_SPELL_TRAP	312
#define COMPLETE_GRAY_SPELL_TRAP	313
#define QUASAR_TRAP	314
#define MOMMA_TRAP	315
#define HORROR_TRAP	316
#define ARTIFICER_TRAP	317
#define WEREFORM_TRAP	318
#define NON_PRAYER_TRAP	319
#define EVIL_PATCH_TRAP	320
#define HARD_MODE_TRAP	321
#define SECRET_ATTACK_TRAP	322
#define EATER_TRAP	323
#define COVETOUSNESS_TRAP	324
#define NOT_SEEN_TRAP	325
#define DARK_MODE_TRAP	326
#define ANTISEARCH_TRAP	327
#define HOMICIDE_TRAP	328
#define NASTY_NATION_TRAP	329
#define WAKEUP_CALL_TRAP	330
#define GRAYOUT_TRAP	331
#define GRAY_CENTER_TRAP	332
#define CHECKERBOARD_TRAP	333
#define CLOCKWISE_SPIN_TRAP	334
#define COUNTERCLOCKWISE_SPIN_TRAP	335
#define LAG_TRAP	336
#define BLESSCURSE_TRAP	337
#define DE_LIGHT_TRAP	338
#define DISCHARGE_TRAP	339
#define TRASHING_TRAP	340
#define FILTERING_TRAP	341
#define DEFORMATTING_TRAP	342
#define FLICKER_STRIP_TRAP	343
#define UNDRESSING_TRAP	344
#define HYPERBLUEWALL_TRAP	345
#define NOLITE_TRAP	346
#define PARANOIA_TRAP	347
#define FLEECESCRIPT_TRAP	348
#define INTERRUPT_TRAP	349
#define DUSTBIN_TRAP	350
#define MANA_BATTERY_TRAP	351
#define MONSTERFINGERS_TRAP	352
#define MISCAST_TRAP	353
#define MESSAGE_SUPPRESSION_TRAP	354
#define STUCK_ANNOUNCEMENT_TRAP	355
#define BLOODTHIRSTY_TRAP	356
#define MAXIMUM_DAMAGE_TRAP	357
#define LATENCY_TRAP	358
#define STARLIT_TRAP	359
#define KNOWLEDGE_TRAP	360
#define HIGHSCORE_TRAP	361
#define PINK_SPELL_TRAP	362
#define GREEN_SPELL_TRAP	363
#define EVC_TRAP	364
#define UNDERLAYER_TRAP	365
#define DAMAGE_METER_TRAP	366
#define ARBITRARY_WEIGHT_TRAP	367
#define FUCKED_INFO_TRAP	368
#define BLACK_SPELL_TRAP	369
#define CYAN_SPELL_TRAP	370
#define HEAP_TRAP	371
#define BLUE_SPELL_TRAP	372
#define TRON_TRAP	373
#define RED_SPELL_TRAP	374
#define TOO_HEAVY_TRAP	375
#define ELONGATION_TRAP	376
#define WRAPOVER_TRAP	377
#define DESTRUCTION_TRAP	378
#define MELEE_PREFIX_TRAP	379
#define AUTOMORE_TRAP	380
#define UNFAIR_ATTACK_TRAP	381

#define KOP_CUBE	382
#define BOSS_SPAWNER	383
#define CONTAMINATION_TRAP	384

#define EVIL_HEEL_TRAP 385
#define BAD_EQUIPMENT_TRAP 386
#define TEMPOCONFLICT_TRAP 387
#define TEMPOHUNGER_TRAP 388
#define TELEPORTITIS_TRAP 389
#define POLYMORPHITIS_TRAP 390
#define PREMATURE_DEATH_TRAP 391
#define LASTING_AMNESIA_TRAP 392
#define RAGNAROK_TRAP 393
#define SINGLE_DISENCHANT_TRAP 394
#define ACID_PIT 395

#define SEVERE_DISENCHANT_TRAP 396
#define PAIN_TRAP 397
#define TREMBLING_TRAP 398
#define TECHCAP_TRAP 399
#define SPELL_MEMORY_TRAP 400
#define SKILL_REDUCTION_TRAP 401
#define SKILLCAP_TRAP 402
#define PERMANENT_STAT_DAMAGE_TRAP 403

#define ORANGE_SPELL_TRAP 404
#define VIOLET_SPELL_TRAP 405
#define TRAP_OF_LONGING 406
#define CURSED_PART_TRAP 407
#define QUAVERSAL_TRAP 408
#define APPEARANCE_SHUFFLING_TRAP 409
#define BROWN_SPELL_TRAP 410
#define CHOICELESS_TRAP 411
#define GOLDSPELL_TRAP 412
#define DEPROVEMENT_TRAP 413
#define INITIALIZATION_TRAP 414
#define GUSHLUSH_TRAP 415
#define SOILTYPE_TRAP 416
#define DANGEROUS_TERRAIN_TRAP 417
#define FALLOUT_TRAP 418
#define MOJIBAKE_TRAP 419
#define GRAVATION_TRAP 420
#define UNCALLED_TRAP 421
#define EXPLODING_DICE_TRAP 422
#define PERMACURSE_TRAP 423
#define SHROUDED_IDENTITY_TRAP 424
#define FEELER_GAUGES_TRAP 425
#define LONG_SCREWUP_TRAP 426
#define WING_YELLOW_CHANGER 427
#define LIFE_SAVING_TRAP 428
#define CURSEUSE_TRAP 429
#define CUT_NUTRITION_TRAP 430
#define SKILL_LOSS_TRAP 431
#define AUTOPILOT_TRAP 432
#define FORCE_TRAP 433
#define MONSTER_GLYPH_TRAP 434
#define CHANGING_DIRECTIVE_TRAP 435
#define CONTAINER_KABOOM_TRAP 436
#define STEAL_DEGRADE_TRAP 437
#define LEFT_INVENTORY_TRAP 438
#define FLUCTUATING_SPEED_TRAP 439
#define TARMUSTROKINGNORA_TRAP 440
#define FAILURE_TRAP 441
#define BRIGHT_CYAN_SPELL_TRAP 442
#define FREQUENTATION_SPAWN_TRAP 443
#define PET_AI_TRAP 444
#define SATAN_TRAP 445
#define REMEMBERANCE_TRAP 446
#define POKELIE_TRAP 447
#define AUTOPICKUP_TRAP 448
#define DYWYPI_TRAP 449
#define SILVER_SPELL_TRAP 450
#define METAL_SPELL_TRAP 451
#define PLATINUM_SPELL_TRAP 452
#define MANLER_TRAP 453
#define DOORNING_TRAP 454
#define NOWNSIBLE_TRAP 455
#define ELM_STREET_TRAP 456
#define MONNOISE_TRAP 457
#define RANG_CALL_TRAP 458
#define RECURRING_SPELL_LOSS_TRAP 459
#define ANTITRAINING_TRAP 460
#define TECHOUT_TRAP 461
#define STAT_DECAY_TRAP 462
#define MOVEMORK_TRAP 463

#define HYBRID_TRAP 464
#define SHAPECHANGE_TRAP 465
#define MELTEM_TRAP 466
#define MIGUC_TRAP 467
#define DIRECTIVE_TRAP 468
#define SATATUE_TRAP 469
#define FARTING_WEB 470
#define CATACLYSM_TRAP 471
#define DATA_DELETE_TRAP 472
#define ELDER_TENTACLING_TRAP 473
#define FOOTERER_TRAP 474

#define BAD_PART_TRAP 475
#define COMPLETELY_BAD_PART_TRAP 476
#define EVIL_VARIANT_TRAP 477

#define GRAVE_WALL_TRAP 478
#define TUNNEL_TRAP 479
#define FARMLAND_TRAP 480
#define MOUNTAIN_TRAP 481
#define WATER_TUNNEL_TRAP 482
#define CRYSTAL_FLOOD_TRAP 483
#define MOORLAND_TRAP 484
#define URINE_TRAP 485
#define SHIFTING_SAND_TRAP 486
#define STYX_TRAP 487
#define PENTAGRAM_TRAP 488
#define SNOW_TRAP 489
#define ASH_TRAP 490
#define SAND_TRAP 491
#define PAVEMENT_TRAP 492
#define HIGHWAY_TRAP 493
#define GRASSLAND_TRAP 494
#define NETHER_MIST_TRAP 495
#define STALACTITE_TRAP 496
#define CRYPTFLOOR_TRAP 497
#define BUBBLE_TRAP 498
#define RAIN_CLOUD_TRAP 499

#define ITEM_NASTIFICATION_TRAP 500
#define SANITY_INCREASE_TRAP 501
#define PSI_TRAP 502
#define GAY_TRAP 503

#define SARAH_TRAP 504
#define CLAUDIA_TRAP 505
#define LUDGERA_TRAP 506
#define KATI_TRAP 507

#define SANITY_TREBLE_TRAP 508
#define STAT_DECREASE_TRAP 509
#define SIMEOUT_TRAP 510
#define S_PRESSING_TRAP 511

#define NELLY_TRAP 512
#define EVELINE_TRAP 513
#define KARIN_TRAP 514
#define JUEN_TRAP 515
#define KRISTINA_TRAP 516
#define LOU_TRAP 517

#define ALMUT_TRAP 518
#define JULIETTA_TRAP 519
#define ARABELLA_TRAP 520

#define KRISTIN_TRAP 521
#define ANNA_TRAP 522
#define RUEA_TRAP 523
#define DORA_TRAP 524
#define MARIKE_TRAP 525
#define JETTE_TRAP 526
#define INA_TRAP 527
#define SING_TRAP 528
#define VICTORIA_TRAP 529
#define MELISSA_TRAP 530
#define ANITA_TRAP 531
#define HENRIETTA_TRAP 532
#define VERENA_TRAP 533

#define ANNEMARIE_TRAP 534
#define JIL_TRAP 535
#define JANA_TRAP 536
#define KATRIN_TRAP 537
#define GUDRUN_TRAP 538
#define ELLA_TRAP 539
#define MANUELA_TRAP 540
#define JENNIFER_TRAP 541
#define PATRICIA_TRAP 542
#define ANTJE_TRAP 543
#define ANTJE_TRAP_X 544
#define KERSTIN_TRAP 545
#define LAURA_TRAP 546
#define LARISSA_TRAP 547
#define NORA_TRAP 548
#define NATALIA_TRAP 549
#define SUSANNE_TRAP 550
#define LISA_TRAP 551
#define BRIDGHITTE_TRAP 552
#define JULIA_TRAP 553
#define NICOLE_TRAP 554
#define RITA_TRAP 555
#define JANINA_TRAP 556
#define ROSA_TRAP 557

#define KSENIA_TRAP 558
#define LYDIA_TRAP 559
#define CONNY_TRAP 560
#define KATIA_TRAP 561
#define MARIYA_TRAP 562
#define ELISE_TRAP 563
#define RONJA_TRAP 564
#define ARIANE_TRAP 565
#define JOHANNA_TRAP 566
#define INGE_TRAP 567

#define WALL_TRAP 568
#define MONSTER_GENERATOR 569
#define POTION_DISPENSER 570
#define SPACEWARS_SPAWN_TRAP 571
#define TV_TROPES_TRAP 572
#define SYMBIOTE_TRAP 573
#define KILL_SYMBIOTE_TRAP 574
#define SYMBIOTE_REPLACEMENT_TRAP 575
#define SHUTDOWN_TRAP 576
#define CORONA_TRAP 577
#define UNPROOFING_TRAP 578
#define VISIBILITY_TRAP 579
#define FEMINISM_STONE_TRAP 580
#define BRANCH_TELEPORTER 581
#define BRANCH_BEAMER 582
#define POISON_ARROW_TRAP 583
#define POISON_BOLT_TRAP 584
#define MACE_TRAP 585
#define SHUEFT_TRAP 586
#define MOTH_LARVAE_TRAP 587
#define WORTHINESS_TRAP 588
#define CONDUCT_TRAP 589
#define STRIKETHROUGH_TRAP 590
#define MULTIPLE_GATHER_TRAP 591
#define VIVISECTION_TRAP 592
#define INSTAFEMINISM_TRAP 593
#define INSTANASTY_TRAP 594
#define SKILL_POINT_LOSS_TRAP 595
#define PERFECT_MATCH_TRAP 596
#define DUMBIE_LIGHTSABER_TRAP 597
#define WRONG_STAIRS 598
#define TECHSTOP_TRAP 599
#define AMNESIA_SWITCH_TRAP 600
#define SKILL_SWAP_TRAP 601
#define SKILL_UPORDOWN_TRAP 602
#define SKILL_RANDOMIZE_TRAP 603

#define SKILL_MULTIPLY_TRAP 604
#define TRAPWALK_TRAP 605
#define CLUSTER_TRAP 606
#define FIELD_TRAP 607
#define MONICIDE_TRAP 608
#define TRAP_CREATION_TRAP 609
#define LEOLD_TRAP 610
#define ANIMEBAND_TRAP 611 /* specialtensmon(325) */
#define PERFUME_TRAP 612 /* specialtensmon(333) */
#define COURT_TRAP 613 /* courtmon() */
#define ELDER_SCROLLS_TRAP 614 /* specialtensmon(427) */
#define JOKE_TRAP 615 /* specialtensmon(323) */
#define DUNGEON_LORDS_TRAP 616 /* specialtensmon(328) */
#define FORTYTWO_TRAP 617 /* douglas_adams_mon() */
#define RANDOMIZE_TRAP 618 /* specialtensmon(331) */
#define EVILROOM_TRAP 619 /* evilroommon() */
#define AOE_TRAP 620 /* specialtensmon(426) */
#define ELONA_TRAP 621 /* specialtensmon(361) */
#define RELIGION_TRAP 622 /* specialtensmon(347) */
#define STEAMBAND_TRAP 623 /* specialtensmon(326) */
#define HARDCORE_TRAP 624 /* specialtensmon(348) */
#define MACHINE_TRAP 625 /* machineroommon() */
#define BEE_TRAP 626 /* beehivemon() */
#define MIGO_TRAP 627 /* migohivemon() */
#define ANGBAND_TRAP 628 /* specialtensmon(324) */
#define DNETHACK_TRAP 629 /* specialtensmon(330) */
#define EVIL_SPAWN_TRAP 630 /* specialtensmon(341) */
#define SHOE_TRAP 631 /* specialtensmon(332) */
#define INSIDE_TRAP 632 /* insidemon() */
#define DOOM_TRAP 633 /* doomsquadmon() */
#define MILITARY_TRAP 634 /* squadmon() */
#define ILLUSION_TRAP 635 /* illusionmon() */
#define DIABLO_TRAP 636 /* specialtensmon(327) */

#define GIANT_EXPLORER_TRAP 637
#define TRAPWARP_TRAP 638
#define YAWM_TRAP 639
#define CRADLE_OF_CHAOS_TRAP 640
#define TEZCATLIPOCA_TRAP 641
#define ENTHUMESIS_TRAP 642
#define MIKRAANESIS_TRAP 643
#define GOTS_TOO_GOOD_TRAP 644
#define KILLER_ROOM_TRAP 645
#define NO_FUN_WALLS_TRAP 646

#define RUTH_TRAP 647
#define MAGDALENA_TRAP 648
#define MARLEEN_TRAP 649
#define KLARA_TRAP 650
#define FRIEDERIKE_TRAP 651
#define NAOMI_TRAP 652
#define UTE_TRAP 653
#define JASIEEN_TRAP 654
#define YASAMAN_TRAP 655
#define MAY_BRITT_TRAP 656

#define CALLING_OUT_TRAP 657
#define FIELD_BREAK_TRAP 658
#define TENTH_TRAP 659
#define DEBT_TRAP 660
#define INVERSION_TRAP 661
#define WINCE_TRAP 662
#define U_HAVE_BEEN_TRAP 663

#define REALLY_BAD_TRAP 664
#define COVID_TRAP 665
#define ARTIBLAST_TRAP 666

#define PERSISTENT_FART_TRAP 667
#define ATTACKING_HEEL_TRAP 668
#define TRAP_TELEPORTER 669
#define ALIGNMENT_TRASH_TRAP 670
#define RESHUFFLE_TRAP 671
#define MUSEHAND_TRAP 672
#define DOGSIDE_TRAP 673
#define BANKRUPT_TRAP 674
#define FILLUP_TRAP 675
#define AIRSTRIKE_TRAP 676
#define DYNAMITE_TRAP 677
#define MALEVOLENCE_TRAP 678
#define LEAFLET_TRAP 679
#define TENTADEEP_TRAP 680
#define STATHALF_TRAP 681
#define CUTSTAT_TRAP 682
#define RARE_SPAWN_TRAP 683
#define YOU_ARE_AN_IDIOT_TRAP 684
#define NASTYCURSE_TRAP 685

#define REPEATING_NASTYCURSE_TRAP 686

#define NADINE_TRAP 687
#define LUISA_TRAP 688
#define IRINA_TRAP 689
#define LISELOTTE_TRAP 690
#define GRETA_TRAP 691
#define JANE_TRAP 692
#define SUE_LYN_TRAP 693
#define CHARLOTTE_TRAP 694
#define HANNAH_TRAP 695
#define LITTLE_MARIE_TRAP 696

#define REAL_LIE_TRAP 697
#define ESCAPE_PAST_TRAP 698
#define PETHATE_TRAP 699
#define PET_LASHOUT_TRAP 700
#define PETSTARVE_TRAP 701
#define PETSCREW_TRAP 702
#define TECH_LOSS_TRAP 703
#define PROOFLOSS_TRAP 704
#define UN_INVIS_TRAP 705
#define DETECTATION_TRAP 706

#define OPTION_TRAP 707
#define MISCOLOR_TRAP 708
#define ONE_RAINBOW_TRAP 709
#define COLORSHIFT_TRAP 710
#define TOP_LINE_TRAP 711
#define CAPS_TRAP 712
#define UN_KNOWLEDGE_TRAP 713
#define DARKHANCE_TRAP 714
#define DSCHUEUEUET_TRAP 715
#define NOPESKILL_TRAP 716
#define FUCKFUCKFUCK_TRAP 717

#define BURDEN_TRAP 718
#define MAGIC_VACUUM_TRAP 719

#define TANJA_TRAP 720
#define SONJA_TRAP 721
#define RHEA_TRAP	722
#define LARA_TRAP	723

#define FUCK_OVER_TRAP 724

#define DAGGER_TRAP 725
#define RAZOR_TRAP 726
#define PHOSGENE_TRAP 727
#define CHLOROFORM_TRAP 728
#define CORROSION_TRAP 729
#define FLAME_TRAP 730
#define WITHER_TRAP 731
#define PHASEPORTER 732
#define PHASE_BEAMER 733
#define VULNERATE_TRAP 734

#define EPVI_TRAP 735

#define SABRINA_TRAP 736

#define AEFDE_TRAP 737

#define FALLING_ROCK_COLD 738
#define RETURN_TRAP 739
#define INTRINSIC_STEAL_TRAP 740
#define SCORE_AXE_TRAP 741
#define SCORE_DRAIN_TRAP 742
#define SINGLE_UNIDENTIFY_TRAP 743
#define HYPOXIC_PIT 744
#define UNLUCKY_TRAP 745
#define ALIGNMENT_REDUCTION_TRAP 746
#define MALIGNANT_TRAP 747
#define STAT_DAMAGE_TRAP 748
#define HALF_MEMORY_TRAP 749
#define HALF_TRAINING_TRAP 750
#define DEBUFF_TRAP 751
#define TRIP_ONCE_TRAP 752
#define NARCOLEPSY_TRAP 753
#define MARTIAL_ARTS_TRAP 754

#define MEAN_BURDEN_TRAP 755
#define CARRCAP_TRAP 756
#define UMENG_TRAP 757

#define SPELL_COOLDOWN_TRAP 758
#define TURBODULL_TRAP 759
#define REDDAM_TRAP 760
#define REDINC_TRAP 761
#define MULCH_TRAP 762
#define INACCURACY_TRAP 763
#define MONSTER_MULTISHOT_TRAP 764
#define DO_YOU_HAVE_A_PIN_TRAP 765
#define COSTLY_FAILURE_TRAP 766
#define INVENTORY_SIZE_TRAP 767

#define SPIKE_TRAP 768
#define PAPER_ARROW_TRAP 769
#define KNIFE_TRAP 770
#define SUMMON_MONSTER_TRAP 771
#define RED_DAMAGE_TRAP 772
#define GREEN_DAMAGE_TRAP 773
#define YELLOW_DAMAGE_TRAP 774
#define WHITE_DAMAGE_TRAP 775
#define BLUE_DAMAGE_TRAP 776
#define MULTI_DEBUFF_TRAP 777

#define MAGIC_DAMAGE_TRAP 778

#define WILD_WEATHER_TRAP 779

#define ANTISWITCH_TRAP 780

#define JANET_TRAP 781

#define BOUND_DAY_CHOICE_TRAP 782

#define SABINE_TRAP 783
#define JUDITH_TRAP 784

#define POKEMON_TRAP 785 /* specialtensmon(140) */

#define ANJA_TRAP 786
#define CELIA_TRAP 787
#define CHLOE_TRAP 788
#define JOHANETTA_TRAP 789

#define ANTIMATTER_TRAP 790

#define ENCLAVE_SPAWNER 791

#define ONE_WAY_PORTAL 792

#define JAVELIN_TRAP 793
#define CLAYMORE_TRAP 794
#define UNICORN_TRAP 795
#define SHOVEL_TRAP 796
#define PICK_AXE_TRAP 797
#define SHIELD_TRAP 798
#define IRON_SHIELD_TRAP 799
#define SLING_TRAP 800
#define BONE_SLING_TRAP 801
#define COBALT_SLING_TRAP 802
#define SHELL_SLING_TRAP 803
#define BRONZE_SLING_TRAP 804
#define GREEN_SLING_TRAP 805
#define BLACK_SLING_TRAP 806
#define AMBER_SLING_TRAP 807

/* todo area

normal ones:

good traps:
#define CHARGING_TRAP
#define LEVELUP_TRAP
#define GAIN_ABILITY_TRAP
#define GOOD_EFFECT_TRAP
#define SKILL_POINT_GAIN_TRAP

nasty traps:

#define EVIL_MIRROR_TRAP
#define ACTION_TIMEOUT_TRAP
#define KILLCAM_TRAP
#define RATCH_TRAP
#define AUTO_ENHANCE_TRAP
#define CURSOR_FAILURE_TRAP
#define DRUNK_CURSOR_TRAP
#define JETLAG_TRAP
#define HARDSHIP_TRAP
#define MONEYSAP_TRAP
#define DROPPORT_TRAP
#define CONTAINER_SPILL_TRAP
#define TELEPORTING_TRAPS_TRAP
#define HARDEST_LAST_LINE_TRAP
#define SUFFIX_TRAP
#define ECHOLESS_TRAP
#define NUPESELL_TRAP
#define BLINKING_LIGHT_TRAP
#define WOEFFOEFF_TRAP
#define PERMA_STATUS_TRAP
#define PERSISTENT_TRAIL_TRAP
#define CONTAINER_SIZE_TRAP
#define VANILLA_SPELL_TRAP
#define STACK_TRAP
#define QUALITY_TRAP
#define ITEMCLICK_TRAP
#define SLOW_PICKUP_TRAP
#define TROPHY_DENY_TRAP
#define BEFORE_THE_NOSE_AWAY_TRAP
#define QUIVER_TRAP
#define UNORGANIZE_TRAP
#define SPEED_UP_AFTER_UNFREEZE_TRAP
#define RENUNCIATION_TRAP
#define BANSHEE_TRAP
#define LOW_HEALTH_TRAP
#define MANAFLUSH_TRAP
#define HOTKEY_TRAP
#define SPARKLE_TRAP
#define NONFUNCTIONING_KNOWLEDGE_TRAP
#define KNOWLEDGE_DECREASE_TRAP
#define VANISHIBUS_TRAP
#define CROSS_AND_CROSSWISE_TRAP
#define IDENTITY_TRAP
#define WAIT_TRAP
#define EROSATING_TRAP
#define CASTING_LIMIT_TRAP
#define FICKYOU_TRAP
#define MOVESPFLOTCH_TRAP
#define SPEED_LIMIT_TRAP
#define FLEECY_HIGHLIGHT_TRAP
#define MONSTER_NASTY_TRAP

#define RANDOM_NASTYTRAP
#define TURBONASTY_TRAP

real weird ones:
#define CURSED_CALLED
#define CED_TRAP
#define KERNEL_S_PORTAL
#define KERNEL_S_STAIRS
#define FARTING_WALL

special ones that don't spawn randomly:
#define TOAD_TRAP

*/

#define TIMERUN_TRAP	808

#define TRAPNUM 809

/* "newtraps" in particular, but also timerun and vulnerate may be targets for grepping --Amy */

#endif /* TRAP_H */
